// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job_desc.proto

package firmament;

public final class JobDesc {
  private JobDesc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JobDescriptorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:firmament.JobDescriptor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
     */
    int getStateValue();
    /**
     * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
     */
    firmament.JobDesc.JobDescriptor.JobState getState();

    /**
     * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
     */
    boolean hasRootTask();
    /**
     * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
     */
    firmament.TaskDesc.TaskDescriptor getRootTask();
    /**
     * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
     */
    firmament.TaskDesc.TaskDescriptorOrBuilder getRootTaskOrBuilder();

    /**
     * <code>repeated bytes output_ids = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getOutputIdsList();
    /**
     * <code>repeated bytes output_ids = 5;</code>
     */
    int getOutputIdsCount();
    /**
     * <code>repeated bytes output_ids = 5;</code>
     */
    com.google.protobuf.ByteString getOutputIds(int index);
  }
  /**
   * Protobuf type {@code firmament.JobDescriptor}
   */
  public  static final class JobDescriptor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:firmament.JobDescriptor)
      JobDescriptorOrBuilder {
    // Use JobDescriptor.newBuilder() to construct.
    private JobDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JobDescriptor() {
      uuid_ = "";
      name_ = "";
      state_ = 0;
      outputIds_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private JobDescriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 34: {
              firmament.TaskDesc.TaskDescriptor.Builder subBuilder = null;
              if (rootTask_ != null) {
                subBuilder = rootTask_.toBuilder();
              }
              rootTask_ = input.readMessage(firmament.TaskDesc.TaskDescriptor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rootTask_);
                rootTask_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                outputIds_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              outputIds_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          outputIds_ = java.util.Collections.unmodifiableList(outputIds_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return firmament.JobDesc.internal_static_firmament_JobDescriptor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return firmament.JobDesc.internal_static_firmament_JobDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              firmament.JobDesc.JobDescriptor.class, firmament.JobDesc.JobDescriptor.Builder.class);
    }

    /**
     * Protobuf enum {@code firmament.JobDescriptor.JobState}
     */
    public enum JobState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NEW = 0;</code>
       */
      NEW(0),
      /**
       * <code>CREATED = 1;</code>
       */
      CREATED(1),
      /**
       * <code>RUNNING = 2;</code>
       */
      RUNNING(2),
      /**
       * <code>COMPLETED = 3;</code>
       */
      COMPLETED(3),
      /**
       * <code>FAILED = 4;</code>
       */
      FAILED(4),
      /**
       * <code>ABORTED = 5;</code>
       */
      ABORTED(5),
      /**
       * <code>UNKNOWN = 6;</code>
       */
      UNKNOWN(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NEW = 0;</code>
       */
      public static final int NEW_VALUE = 0;
      /**
       * <code>CREATED = 1;</code>
       */
      public static final int CREATED_VALUE = 1;
      /**
       * <code>RUNNING = 2;</code>
       */
      public static final int RUNNING_VALUE = 2;
      /**
       * <code>COMPLETED = 3;</code>
       */
      public static final int COMPLETED_VALUE = 3;
      /**
       * <code>FAILED = 4;</code>
       */
      public static final int FAILED_VALUE = 4;
      /**
       * <code>ABORTED = 5;</code>
       */
      public static final int ABORTED_VALUE = 5;
      /**
       * <code>UNKNOWN = 6;</code>
       */
      public static final int UNKNOWN_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static JobState valueOf(int value) {
        return forNumber(value);
      }

      public static JobState forNumber(int value) {
        switch (value) {
          case 0: return NEW;
          case 1: return CREATED;
          case 2: return RUNNING;
          case 3: return COMPLETED;
          case 4: return FAILED;
          case 5: return ABORTED;
          case 6: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<JobState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          JobState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<JobState>() {
              public JobState findValueByNumber(int number) {
                return JobState.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return firmament.JobDesc.JobDescriptor.getDescriptor().getEnumTypes().get(0);
      }

      private static final JobState[] VALUES = values();

      public static JobState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private JobState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:firmament.JobDescriptor.JobState)
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    /**
     * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
     */
    public firmament.JobDesc.JobDescriptor.JobState getState() {
      firmament.JobDesc.JobDescriptor.JobState result = firmament.JobDesc.JobDescriptor.JobState.valueOf(state_);
      return result == null ? firmament.JobDesc.JobDescriptor.JobState.UNRECOGNIZED : result;
    }

    public static final int ROOT_TASK_FIELD_NUMBER = 4;
    private firmament.TaskDesc.TaskDescriptor rootTask_;
    /**
     * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
     */
    public boolean hasRootTask() {
      return rootTask_ != null;
    }
    /**
     * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
     */
    public firmament.TaskDesc.TaskDescriptor getRootTask() {
      return rootTask_ == null ? firmament.TaskDesc.TaskDescriptor.getDefaultInstance() : rootTask_;
    }
    /**
     * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
     */
    public firmament.TaskDesc.TaskDescriptorOrBuilder getRootTaskOrBuilder() {
      return getRootTask();
    }

    public static final int OUTPUT_IDS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> outputIds_;
    /**
     * <code>repeated bytes output_ids = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getOutputIdsList() {
      return outputIds_;
    }
    /**
     * <code>repeated bytes output_ids = 5;</code>
     */
    public int getOutputIdsCount() {
      return outputIds_.size();
    }
    /**
     * <code>repeated bytes output_ids = 5;</code>
     */
    public com.google.protobuf.ByteString getOutputIds(int index) {
      return outputIds_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (state_ != firmament.JobDesc.JobDescriptor.JobState.NEW.getNumber()) {
        output.writeEnum(3, state_);
      }
      if (rootTask_ != null) {
        output.writeMessage(4, getRootTask());
      }
      for (int i = 0; i < outputIds_.size(); i++) {
        output.writeBytes(5, outputIds_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (state_ != firmament.JobDesc.JobDescriptor.JobState.NEW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, state_);
      }
      if (rootTask_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getRootTask());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < outputIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(outputIds_.get(i));
        }
        size += dataSize;
        size += 1 * getOutputIdsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof firmament.JobDesc.JobDescriptor)) {
        return super.equals(obj);
      }
      firmament.JobDesc.JobDescriptor other = (firmament.JobDesc.JobDescriptor) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && getName()
          .equals(other.getName());
      result = result && state_ == other.state_;
      result = result && (hasRootTask() == other.hasRootTask());
      if (hasRootTask()) {
        result = result && getRootTask()
            .equals(other.getRootTask());
      }
      result = result && getOutputIdsList()
          .equals(other.getOutputIdsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      if (hasRootTask()) {
        hash = (37 * hash) + ROOT_TASK_FIELD_NUMBER;
        hash = (53 * hash) + getRootTask().hashCode();
      }
      if (getOutputIdsCount() > 0) {
        hash = (37 * hash) + OUTPUT_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getOutputIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static firmament.JobDesc.JobDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.JobDesc.JobDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.JobDesc.JobDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.JobDesc.JobDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.JobDesc.JobDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.JobDesc.JobDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.JobDesc.JobDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static firmament.JobDesc.JobDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.JobDesc.JobDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.JobDesc.JobDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(firmament.JobDesc.JobDescriptor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code firmament.JobDescriptor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:firmament.JobDescriptor)
        firmament.JobDesc.JobDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return firmament.JobDesc.internal_static_firmament_JobDescriptor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return firmament.JobDesc.internal_static_firmament_JobDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                firmament.JobDesc.JobDescriptor.class, firmament.JobDesc.JobDescriptor.Builder.class);
      }

      // Construct using firmament.JobDesc.JobDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        name_ = "";

        state_ = 0;

        if (rootTaskBuilder_ == null) {
          rootTask_ = null;
        } else {
          rootTask_ = null;
          rootTaskBuilder_ = null;
        }
        outputIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return firmament.JobDesc.internal_static_firmament_JobDescriptor_descriptor;
      }

      public firmament.JobDesc.JobDescriptor getDefaultInstanceForType() {
        return firmament.JobDesc.JobDescriptor.getDefaultInstance();
      }

      public firmament.JobDesc.JobDescriptor build() {
        firmament.JobDesc.JobDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public firmament.JobDesc.JobDescriptor buildPartial() {
        firmament.JobDesc.JobDescriptor result = new firmament.JobDesc.JobDescriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uuid_ = uuid_;
        result.name_ = name_;
        result.state_ = state_;
        if (rootTaskBuilder_ == null) {
          result.rootTask_ = rootTask_;
        } else {
          result.rootTask_ = rootTaskBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          outputIds_ = java.util.Collections.unmodifiableList(outputIds_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.outputIds_ = outputIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof firmament.JobDesc.JobDescriptor) {
          return mergeFrom((firmament.JobDesc.JobDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(firmament.JobDesc.JobDescriptor other) {
        if (other == firmament.JobDesc.JobDescriptor.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.hasRootTask()) {
          mergeRootTask(other.getRootTask());
        }
        if (!other.outputIds_.isEmpty()) {
          if (outputIds_.isEmpty()) {
            outputIds_ = other.outputIds_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureOutputIdsIsMutable();
            outputIds_.addAll(other.outputIds_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        firmament.JobDesc.JobDescriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (firmament.JobDesc.JobDescriptor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
       */
      public firmament.JobDesc.JobDescriptor.JobState getState() {
        firmament.JobDesc.JobDescriptor.JobState result = firmament.JobDesc.JobDescriptor.JobState.valueOf(state_);
        return result == null ? firmament.JobDesc.JobDescriptor.JobState.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
       */
      public Builder setState(firmament.JobDesc.JobDescriptor.JobState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .firmament.JobDescriptor.JobState state = 3;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private firmament.TaskDesc.TaskDescriptor rootTask_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          firmament.TaskDesc.TaskDescriptor, firmament.TaskDesc.TaskDescriptor.Builder, firmament.TaskDesc.TaskDescriptorOrBuilder> rootTaskBuilder_;
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public boolean hasRootTask() {
        return rootTaskBuilder_ != null || rootTask_ != null;
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public firmament.TaskDesc.TaskDescriptor getRootTask() {
        if (rootTaskBuilder_ == null) {
          return rootTask_ == null ? firmament.TaskDesc.TaskDescriptor.getDefaultInstance() : rootTask_;
        } else {
          return rootTaskBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public Builder setRootTask(firmament.TaskDesc.TaskDescriptor value) {
        if (rootTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rootTask_ = value;
          onChanged();
        } else {
          rootTaskBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public Builder setRootTask(
          firmament.TaskDesc.TaskDescriptor.Builder builderForValue) {
        if (rootTaskBuilder_ == null) {
          rootTask_ = builderForValue.build();
          onChanged();
        } else {
          rootTaskBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public Builder mergeRootTask(firmament.TaskDesc.TaskDescriptor value) {
        if (rootTaskBuilder_ == null) {
          if (rootTask_ != null) {
            rootTask_ =
              firmament.TaskDesc.TaskDescriptor.newBuilder(rootTask_).mergeFrom(value).buildPartial();
          } else {
            rootTask_ = value;
          }
          onChanged();
        } else {
          rootTaskBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public Builder clearRootTask() {
        if (rootTaskBuilder_ == null) {
          rootTask_ = null;
          onChanged();
        } else {
          rootTask_ = null;
          rootTaskBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public firmament.TaskDesc.TaskDescriptor.Builder getRootTaskBuilder() {
        
        onChanged();
        return getRootTaskFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      public firmament.TaskDesc.TaskDescriptorOrBuilder getRootTaskOrBuilder() {
        if (rootTaskBuilder_ != null) {
          return rootTaskBuilder_.getMessageOrBuilder();
        } else {
          return rootTask_ == null ?
              firmament.TaskDesc.TaskDescriptor.getDefaultInstance() : rootTask_;
        }
      }
      /**
       * <code>optional .firmament.TaskDescriptor root_task = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          firmament.TaskDesc.TaskDescriptor, firmament.TaskDesc.TaskDescriptor.Builder, firmament.TaskDesc.TaskDescriptorOrBuilder> 
          getRootTaskFieldBuilder() {
        if (rootTaskBuilder_ == null) {
          rootTaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              firmament.TaskDesc.TaskDescriptor, firmament.TaskDesc.TaskDescriptor.Builder, firmament.TaskDesc.TaskDescriptorOrBuilder>(
                  getRootTask(),
                  getParentForChildren(),
                  isClean());
          rootTask_ = null;
        }
        return rootTaskBuilder_;
      }

      private java.util.List<com.google.protobuf.ByteString> outputIds_ = java.util.Collections.emptyList();
      private void ensureOutputIdsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          outputIds_ = new java.util.ArrayList<com.google.protobuf.ByteString>(outputIds_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes output_ids = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getOutputIdsList() {
        return java.util.Collections.unmodifiableList(outputIds_);
      }
      /**
       * <code>repeated bytes output_ids = 5;</code>
       */
      public int getOutputIdsCount() {
        return outputIds_.size();
      }
      /**
       * <code>repeated bytes output_ids = 5;</code>
       */
      public com.google.protobuf.ByteString getOutputIds(int index) {
        return outputIds_.get(index);
      }
      /**
       * <code>repeated bytes output_ids = 5;</code>
       */
      public Builder setOutputIds(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputIdsIsMutable();
        outputIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes output_ids = 5;</code>
       */
      public Builder addOutputIds(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputIdsIsMutable();
        outputIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes output_ids = 5;</code>
       */
      public Builder addAllOutputIds(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureOutputIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outputIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes output_ids = 5;</code>
       */
      public Builder clearOutputIds() {
        outputIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:firmament.JobDescriptor)
    }

    // @@protoc_insertion_point(class_scope:firmament.JobDescriptor)
    private static final firmament.JobDesc.JobDescriptor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new firmament.JobDesc.JobDescriptor();
    }

    public static firmament.JobDesc.JobDescriptor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JobDescriptor>
        PARSER = new com.google.protobuf.AbstractParser<JobDescriptor>() {
      public JobDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new JobDescriptor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JobDescriptor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JobDescriptor> getParserForType() {
      return PARSER;
    }

    public firmament.JobDesc.JobDescriptor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firmament_JobDescriptor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firmament_JobDescriptor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016job_desc.proto\022\tfirmament\032\017task_desc.p" +
      "roto\"\203\002\n\rJobDescriptor\022\014\n\004uuid\030\001 \001(\t\022\014\n\004" +
      "name\030\002 \001(\t\0220\n\005state\030\003 \001(\0162!.firmament.Jo" +
      "bDescriptor.JobState\022,\n\troot_task\030\004 \001(\0132" +
      "\031.firmament.TaskDescriptor\022\022\n\noutput_ids" +
      "\030\005 \003(\014\"b\n\010JobState\022\007\n\003NEW\020\000\022\013\n\007CREATED\020\001" +
      "\022\013\n\007RUNNING\020\002\022\r\n\tCOMPLETED\020\003\022\n\n\006FAILED\020\004" +
      "\022\013\n\007ABORTED\020\005\022\013\n\007UNKNOWN\020\006b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          firmament.TaskDesc.getDescriptor(),
        }, assigner);
    internal_static_firmament_JobDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_firmament_JobDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firmament_JobDescriptor_descriptor,
        new java.lang.String[] { "Uuid", "Name", "State", "RootTask", "OutputIds", });
    firmament.TaskDesc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
