// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_stats.proto

package firmament;

public final class ResourceStatsOuterClass {
  private ResourceStatsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResourceStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:firmament.ResourceStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string resource_id = 1;</code>
     */
    java.lang.String getResourceId();
    /**
     * <code>optional string resource_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getResourceIdBytes();

    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    java.util.List<firmament.ResourceStatsOuterClass.CpuStats> 
        getCpusStatsList();
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    firmament.ResourceStatsOuterClass.CpuStats getCpusStats(int index);
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    int getCpusStatsCount();
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    java.util.List<? extends firmament.ResourceStatsOuterClass.CpuStatsOrBuilder> 
        getCpusStatsOrBuilderList();
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    firmament.ResourceStatsOuterClass.CpuStatsOrBuilder getCpusStatsOrBuilder(
        int index);

    /**
     * <pre>
     * Memory stats (in KB).
     * </pre>
     *
     * <code>optional int64 mem_allocatable = 4;</code>
     */
    long getMemAllocatable();

    /**
     * <code>optional int64 mem_capacity = 5;</code>
     */
    long getMemCapacity();

    /**
     * <pre>
     * Memory stats (fraction of total).
     * </pre>
     *
     * <code>optional double mem_reservation = 6;</code>
     */
    double getMemReservation();

    /**
     * <code>optional double mem_utilization = 7;</code>
     */
    double getMemUtilization();

    /**
     * <pre>
     * Disk stats in KB
     * </pre>
     *
     * <code>optional int64 disk_bw = 8;</code>
     */
    long getDiskBw();

    /**
     * <pre>
     * Network stats in KB
     * </pre>
     *
     * <code>optional int64 net_rx_bw = 9;</code>
     */
    long getNetRxBw();

    /**
     * <code>optional int64 net_tx_bw = 10;</code>
     */
    long getNetTxBw();
  }
  /**
   * Protobuf type {@code firmament.ResourceStats}
   */
  public  static final class ResourceStats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:firmament.ResourceStats)
      ResourceStatsOrBuilder {
    // Use ResourceStats.newBuilder() to construct.
    private ResourceStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResourceStats() {
      resourceId_ = "";
      timestamp_ = 0L;
      cpusStats_ = java.util.Collections.emptyList();
      memAllocatable_ = 0L;
      memCapacity_ = 0L;
      memReservation_ = 0D;
      memUtilization_ = 0D;
      diskBw_ = 0L;
      netRxBw_ = 0L;
      netTxBw_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResourceStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              resourceId_ = s;
              break;
            }
            case 16: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                cpusStats_ = new java.util.ArrayList<firmament.ResourceStatsOuterClass.CpuStats>();
                mutable_bitField0_ |= 0x00000004;
              }
              cpusStats_.add(
                  input.readMessage(firmament.ResourceStatsOuterClass.CpuStats.parser(), extensionRegistry));
              break;
            }
            case 32: {

              memAllocatable_ = input.readInt64();
              break;
            }
            case 40: {

              memCapacity_ = input.readInt64();
              break;
            }
            case 49: {

              memReservation_ = input.readDouble();
              break;
            }
            case 57: {

              memUtilization_ = input.readDouble();
              break;
            }
            case 64: {

              diskBw_ = input.readInt64();
              break;
            }
            case 72: {

              netRxBw_ = input.readInt64();
              break;
            }
            case 80: {

              netTxBw_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          cpusStats_ = java.util.Collections.unmodifiableList(cpusStats_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return firmament.ResourceStatsOuterClass.internal_static_firmament_ResourceStats_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return firmament.ResourceStatsOuterClass.internal_static_firmament_ResourceStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              firmament.ResourceStatsOuterClass.ResourceStats.class, firmament.ResourceStatsOuterClass.ResourceStats.Builder.class);
    }

    private int bitField0_;
    public static final int RESOURCE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object resourceId_;
    /**
     * <code>optional string resource_id = 1;</code>
     */
    public java.lang.String getResourceId() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resource_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CPUS_STATS_FIELD_NUMBER = 3;
    private java.util.List<firmament.ResourceStatsOuterClass.CpuStats> cpusStats_;
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    public java.util.List<firmament.ResourceStatsOuterClass.CpuStats> getCpusStatsList() {
      return cpusStats_;
    }
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    public java.util.List<? extends firmament.ResourceStatsOuterClass.CpuStatsOrBuilder> 
        getCpusStatsOrBuilderList() {
      return cpusStats_;
    }
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    public int getCpusStatsCount() {
      return cpusStats_.size();
    }
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    public firmament.ResourceStatsOuterClass.CpuStats getCpusStats(int index) {
      return cpusStats_.get(index);
    }
    /**
     * <pre>
     * The first entry is the cpu usage of cpu0 and so on.
     * </pre>
     *
     * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
     */
    public firmament.ResourceStatsOuterClass.CpuStatsOrBuilder getCpusStatsOrBuilder(
        int index) {
      return cpusStats_.get(index);
    }

    public static final int MEM_ALLOCATABLE_FIELD_NUMBER = 4;
    private long memAllocatable_;
    /**
     * <pre>
     * Memory stats (in KB).
     * </pre>
     *
     * <code>optional int64 mem_allocatable = 4;</code>
     */
    public long getMemAllocatable() {
      return memAllocatable_;
    }

    public static final int MEM_CAPACITY_FIELD_NUMBER = 5;
    private long memCapacity_;
    /**
     * <code>optional int64 mem_capacity = 5;</code>
     */
    public long getMemCapacity() {
      return memCapacity_;
    }

    public static final int MEM_RESERVATION_FIELD_NUMBER = 6;
    private double memReservation_;
    /**
     * <pre>
     * Memory stats (fraction of total).
     * </pre>
     *
     * <code>optional double mem_reservation = 6;</code>
     */
    public double getMemReservation() {
      return memReservation_;
    }

    public static final int MEM_UTILIZATION_FIELD_NUMBER = 7;
    private double memUtilization_;
    /**
     * <code>optional double mem_utilization = 7;</code>
     */
    public double getMemUtilization() {
      return memUtilization_;
    }

    public static final int DISK_BW_FIELD_NUMBER = 8;
    private long diskBw_;
    /**
     * <pre>
     * Disk stats in KB
     * </pre>
     *
     * <code>optional int64 disk_bw = 8;</code>
     */
    public long getDiskBw() {
      return diskBw_;
    }

    public static final int NET_RX_BW_FIELD_NUMBER = 9;
    private long netRxBw_;
    /**
     * <pre>
     * Network stats in KB
     * </pre>
     *
     * <code>optional int64 net_rx_bw = 9;</code>
     */
    public long getNetRxBw() {
      return netRxBw_;
    }

    public static final int NET_TX_BW_FIELD_NUMBER = 10;
    private long netTxBw_;
    /**
     * <code>optional int64 net_tx_bw = 10;</code>
     */
    public long getNetTxBw() {
      return netTxBw_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResourceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceId_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(2, timestamp_);
      }
      for (int i = 0; i < cpusStats_.size(); i++) {
        output.writeMessage(3, cpusStats_.get(i));
      }
      if (memAllocatable_ != 0L) {
        output.writeInt64(4, memAllocatable_);
      }
      if (memCapacity_ != 0L) {
        output.writeInt64(5, memCapacity_);
      }
      if (memReservation_ != 0D) {
        output.writeDouble(6, memReservation_);
      }
      if (memUtilization_ != 0D) {
        output.writeDouble(7, memUtilization_);
      }
      if (diskBw_ != 0L) {
        output.writeInt64(8, diskBw_);
      }
      if (netRxBw_ != 0L) {
        output.writeInt64(9, netRxBw_);
      }
      if (netTxBw_ != 0L) {
        output.writeInt64(10, netTxBw_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResourceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      for (int i = 0; i < cpusStats_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, cpusStats_.get(i));
      }
      if (memAllocatable_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, memAllocatable_);
      }
      if (memCapacity_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, memCapacity_);
      }
      if (memReservation_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, memReservation_);
      }
      if (memUtilization_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, memUtilization_);
      }
      if (diskBw_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, diskBw_);
      }
      if (netRxBw_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, netRxBw_);
      }
      if (netTxBw_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, netTxBw_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof firmament.ResourceStatsOuterClass.ResourceStats)) {
        return super.equals(obj);
      }
      firmament.ResourceStatsOuterClass.ResourceStats other = (firmament.ResourceStatsOuterClass.ResourceStats) obj;

      boolean result = true;
      result = result && getResourceId()
          .equals(other.getResourceId());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getCpusStatsList()
          .equals(other.getCpusStatsList());
      result = result && (getMemAllocatable()
          == other.getMemAllocatable());
      result = result && (getMemCapacity()
          == other.getMemCapacity());
      result = result && (
          java.lang.Double.doubleToLongBits(getMemReservation())
          == java.lang.Double.doubleToLongBits(
              other.getMemReservation()));
      result = result && (
          java.lang.Double.doubleToLongBits(getMemUtilization())
          == java.lang.Double.doubleToLongBits(
              other.getMemUtilization()));
      result = result && (getDiskBw()
          == other.getDiskBw());
      result = result && (getNetRxBw()
          == other.getNetRxBw());
      result = result && (getNetTxBw()
          == other.getNetTxBw());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getResourceId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      if (getCpusStatsCount() > 0) {
        hash = (37 * hash) + CPUS_STATS_FIELD_NUMBER;
        hash = (53 * hash) + getCpusStatsList().hashCode();
      }
      hash = (37 * hash) + MEM_ALLOCATABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemAllocatable());
      hash = (37 * hash) + MEM_CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemCapacity());
      hash = (37 * hash) + MEM_RESERVATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMemReservation()));
      hash = (37 * hash) + MEM_UTILIZATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMemUtilization()));
      hash = (37 * hash) + DISK_BW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDiskBw());
      hash = (37 * hash) + NET_RX_BW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNetRxBw());
      hash = (37 * hash) + NET_TX_BW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNetTxBw());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.ResourceStatsOuterClass.ResourceStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(firmament.ResourceStatsOuterClass.ResourceStats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code firmament.ResourceStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:firmament.ResourceStats)
        firmament.ResourceStatsOuterClass.ResourceStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return firmament.ResourceStatsOuterClass.internal_static_firmament_ResourceStats_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return firmament.ResourceStatsOuterClass.internal_static_firmament_ResourceStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                firmament.ResourceStatsOuterClass.ResourceStats.class, firmament.ResourceStatsOuterClass.ResourceStats.Builder.class);
      }

      // Construct using firmament.ResourceStatsOuterClass.ResourceStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCpusStatsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        resourceId_ = "";

        timestamp_ = 0L;

        if (cpusStatsBuilder_ == null) {
          cpusStats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          cpusStatsBuilder_.clear();
        }
        memAllocatable_ = 0L;

        memCapacity_ = 0L;

        memReservation_ = 0D;

        memUtilization_ = 0D;

        diskBw_ = 0L;

        netRxBw_ = 0L;

        netTxBw_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return firmament.ResourceStatsOuterClass.internal_static_firmament_ResourceStats_descriptor;
      }

      public firmament.ResourceStatsOuterClass.ResourceStats getDefaultInstanceForType() {
        return firmament.ResourceStatsOuterClass.ResourceStats.getDefaultInstance();
      }

      public firmament.ResourceStatsOuterClass.ResourceStats build() {
        firmament.ResourceStatsOuterClass.ResourceStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public firmament.ResourceStatsOuterClass.ResourceStats buildPartial() {
        firmament.ResourceStatsOuterClass.ResourceStats result = new firmament.ResourceStatsOuterClass.ResourceStats(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.resourceId_ = resourceId_;
        result.timestamp_ = timestamp_;
        if (cpusStatsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            cpusStats_ = java.util.Collections.unmodifiableList(cpusStats_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.cpusStats_ = cpusStats_;
        } else {
          result.cpusStats_ = cpusStatsBuilder_.build();
        }
        result.memAllocatable_ = memAllocatable_;
        result.memCapacity_ = memCapacity_;
        result.memReservation_ = memReservation_;
        result.memUtilization_ = memUtilization_;
        result.diskBw_ = diskBw_;
        result.netRxBw_ = netRxBw_;
        result.netTxBw_ = netTxBw_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof firmament.ResourceStatsOuterClass.ResourceStats) {
          return mergeFrom((firmament.ResourceStatsOuterClass.ResourceStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(firmament.ResourceStatsOuterClass.ResourceStats other) {
        if (other == firmament.ResourceStatsOuterClass.ResourceStats.getDefaultInstance()) return this;
        if (!other.getResourceId().isEmpty()) {
          resourceId_ = other.resourceId_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (cpusStatsBuilder_ == null) {
          if (!other.cpusStats_.isEmpty()) {
            if (cpusStats_.isEmpty()) {
              cpusStats_ = other.cpusStats_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureCpusStatsIsMutable();
              cpusStats_.addAll(other.cpusStats_);
            }
            onChanged();
          }
        } else {
          if (!other.cpusStats_.isEmpty()) {
            if (cpusStatsBuilder_.isEmpty()) {
              cpusStatsBuilder_.dispose();
              cpusStatsBuilder_ = null;
              cpusStats_ = other.cpusStats_;
              bitField0_ = (bitField0_ & ~0x00000004);
              cpusStatsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCpusStatsFieldBuilder() : null;
            } else {
              cpusStatsBuilder_.addAllMessages(other.cpusStats_);
            }
          }
        }
        if (other.getMemAllocatable() != 0L) {
          setMemAllocatable(other.getMemAllocatable());
        }
        if (other.getMemCapacity() != 0L) {
          setMemCapacity(other.getMemCapacity());
        }
        if (other.getMemReservation() != 0D) {
          setMemReservation(other.getMemReservation());
        }
        if (other.getMemUtilization() != 0D) {
          setMemUtilization(other.getMemUtilization());
        }
        if (other.getDiskBw() != 0L) {
          setDiskBw(other.getDiskBw());
        }
        if (other.getNetRxBw() != 0L) {
          setNetRxBw(other.getNetRxBw());
        }
        if (other.getNetTxBw() != 0L) {
          setNetTxBw(other.getNetTxBw());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        firmament.ResourceStatsOuterClass.ResourceStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (firmament.ResourceStatsOuterClass.ResourceStats) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object resourceId_ = "";
      /**
       * <code>optional string resource_id = 1;</code>
       */
      public java.lang.String getResourceId() {
        java.lang.Object ref = resourceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resourceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resource_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResourceIdBytes() {
        java.lang.Object ref = resourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resource_id = 1;</code>
       */
      public Builder setResourceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resource_id = 1;</code>
       */
      public Builder clearResourceId() {
        
        resourceId_ = getDefaultInstance().getResourceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resource_id = 1;</code>
       */
      public Builder setResourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resourceId_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<firmament.ResourceStatsOuterClass.CpuStats> cpusStats_ =
        java.util.Collections.emptyList();
      private void ensureCpusStatsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          cpusStats_ = new java.util.ArrayList<firmament.ResourceStatsOuterClass.CpuStats>(cpusStats_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          firmament.ResourceStatsOuterClass.CpuStats, firmament.ResourceStatsOuterClass.CpuStats.Builder, firmament.ResourceStatsOuterClass.CpuStatsOrBuilder> cpusStatsBuilder_;

      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public java.util.List<firmament.ResourceStatsOuterClass.CpuStats> getCpusStatsList() {
        if (cpusStatsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cpusStats_);
        } else {
          return cpusStatsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public int getCpusStatsCount() {
        if (cpusStatsBuilder_ == null) {
          return cpusStats_.size();
        } else {
          return cpusStatsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public firmament.ResourceStatsOuterClass.CpuStats getCpusStats(int index) {
        if (cpusStatsBuilder_ == null) {
          return cpusStats_.get(index);
        } else {
          return cpusStatsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder setCpusStats(
          int index, firmament.ResourceStatsOuterClass.CpuStats value) {
        if (cpusStatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCpusStatsIsMutable();
          cpusStats_.set(index, value);
          onChanged();
        } else {
          cpusStatsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder setCpusStats(
          int index, firmament.ResourceStatsOuterClass.CpuStats.Builder builderForValue) {
        if (cpusStatsBuilder_ == null) {
          ensureCpusStatsIsMutable();
          cpusStats_.set(index, builderForValue.build());
          onChanged();
        } else {
          cpusStatsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder addCpusStats(firmament.ResourceStatsOuterClass.CpuStats value) {
        if (cpusStatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCpusStatsIsMutable();
          cpusStats_.add(value);
          onChanged();
        } else {
          cpusStatsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder addCpusStats(
          int index, firmament.ResourceStatsOuterClass.CpuStats value) {
        if (cpusStatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCpusStatsIsMutable();
          cpusStats_.add(index, value);
          onChanged();
        } else {
          cpusStatsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder addCpusStats(
          firmament.ResourceStatsOuterClass.CpuStats.Builder builderForValue) {
        if (cpusStatsBuilder_ == null) {
          ensureCpusStatsIsMutable();
          cpusStats_.add(builderForValue.build());
          onChanged();
        } else {
          cpusStatsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder addCpusStats(
          int index, firmament.ResourceStatsOuterClass.CpuStats.Builder builderForValue) {
        if (cpusStatsBuilder_ == null) {
          ensureCpusStatsIsMutable();
          cpusStats_.add(index, builderForValue.build());
          onChanged();
        } else {
          cpusStatsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder addAllCpusStats(
          java.lang.Iterable<? extends firmament.ResourceStatsOuterClass.CpuStats> values) {
        if (cpusStatsBuilder_ == null) {
          ensureCpusStatsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cpusStats_);
          onChanged();
        } else {
          cpusStatsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder clearCpusStats() {
        if (cpusStatsBuilder_ == null) {
          cpusStats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          cpusStatsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public Builder removeCpusStats(int index) {
        if (cpusStatsBuilder_ == null) {
          ensureCpusStatsIsMutable();
          cpusStats_.remove(index);
          onChanged();
        } else {
          cpusStatsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public firmament.ResourceStatsOuterClass.CpuStats.Builder getCpusStatsBuilder(
          int index) {
        return getCpusStatsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public firmament.ResourceStatsOuterClass.CpuStatsOrBuilder getCpusStatsOrBuilder(
          int index) {
        if (cpusStatsBuilder_ == null) {
          return cpusStats_.get(index);  } else {
          return cpusStatsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public java.util.List<? extends firmament.ResourceStatsOuterClass.CpuStatsOrBuilder> 
           getCpusStatsOrBuilderList() {
        if (cpusStatsBuilder_ != null) {
          return cpusStatsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cpusStats_);
        }
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public firmament.ResourceStatsOuterClass.CpuStats.Builder addCpusStatsBuilder() {
        return getCpusStatsFieldBuilder().addBuilder(
            firmament.ResourceStatsOuterClass.CpuStats.getDefaultInstance());
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public firmament.ResourceStatsOuterClass.CpuStats.Builder addCpusStatsBuilder(
          int index) {
        return getCpusStatsFieldBuilder().addBuilder(
            index, firmament.ResourceStatsOuterClass.CpuStats.getDefaultInstance());
      }
      /**
       * <pre>
       * The first entry is the cpu usage of cpu0 and so on.
       * </pre>
       *
       * <code>repeated .firmament.CpuStats cpus_stats = 3;</code>
       */
      public java.util.List<firmament.ResourceStatsOuterClass.CpuStats.Builder> 
           getCpusStatsBuilderList() {
        return getCpusStatsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          firmament.ResourceStatsOuterClass.CpuStats, firmament.ResourceStatsOuterClass.CpuStats.Builder, firmament.ResourceStatsOuterClass.CpuStatsOrBuilder> 
          getCpusStatsFieldBuilder() {
        if (cpusStatsBuilder_ == null) {
          cpusStatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              firmament.ResourceStatsOuterClass.CpuStats, firmament.ResourceStatsOuterClass.CpuStats.Builder, firmament.ResourceStatsOuterClass.CpuStatsOrBuilder>(
                  cpusStats_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          cpusStats_ = null;
        }
        return cpusStatsBuilder_;
      }

      private long memAllocatable_ ;
      /**
       * <pre>
       * Memory stats (in KB).
       * </pre>
       *
       * <code>optional int64 mem_allocatable = 4;</code>
       */
      public long getMemAllocatable() {
        return memAllocatable_;
      }
      /**
       * <pre>
       * Memory stats (in KB).
       * </pre>
       *
       * <code>optional int64 mem_allocatable = 4;</code>
       */
      public Builder setMemAllocatable(long value) {
        
        memAllocatable_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Memory stats (in KB).
       * </pre>
       *
       * <code>optional int64 mem_allocatable = 4;</code>
       */
      public Builder clearMemAllocatable() {
        
        memAllocatable_ = 0L;
        onChanged();
        return this;
      }

      private long memCapacity_ ;
      /**
       * <code>optional int64 mem_capacity = 5;</code>
       */
      public long getMemCapacity() {
        return memCapacity_;
      }
      /**
       * <code>optional int64 mem_capacity = 5;</code>
       */
      public Builder setMemCapacity(long value) {
        
        memCapacity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mem_capacity = 5;</code>
       */
      public Builder clearMemCapacity() {
        
        memCapacity_ = 0L;
        onChanged();
        return this;
      }

      private double memReservation_ ;
      /**
       * <pre>
       * Memory stats (fraction of total).
       * </pre>
       *
       * <code>optional double mem_reservation = 6;</code>
       */
      public double getMemReservation() {
        return memReservation_;
      }
      /**
       * <pre>
       * Memory stats (fraction of total).
       * </pre>
       *
       * <code>optional double mem_reservation = 6;</code>
       */
      public Builder setMemReservation(double value) {
        
        memReservation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Memory stats (fraction of total).
       * </pre>
       *
       * <code>optional double mem_reservation = 6;</code>
       */
      public Builder clearMemReservation() {
        
        memReservation_ = 0D;
        onChanged();
        return this;
      }

      private double memUtilization_ ;
      /**
       * <code>optional double mem_utilization = 7;</code>
       */
      public double getMemUtilization() {
        return memUtilization_;
      }
      /**
       * <code>optional double mem_utilization = 7;</code>
       */
      public Builder setMemUtilization(double value) {
        
        memUtilization_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double mem_utilization = 7;</code>
       */
      public Builder clearMemUtilization() {
        
        memUtilization_ = 0D;
        onChanged();
        return this;
      }

      private long diskBw_ ;
      /**
       * <pre>
       * Disk stats in KB
       * </pre>
       *
       * <code>optional int64 disk_bw = 8;</code>
       */
      public long getDiskBw() {
        return diskBw_;
      }
      /**
       * <pre>
       * Disk stats in KB
       * </pre>
       *
       * <code>optional int64 disk_bw = 8;</code>
       */
      public Builder setDiskBw(long value) {
        
        diskBw_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Disk stats in KB
       * </pre>
       *
       * <code>optional int64 disk_bw = 8;</code>
       */
      public Builder clearDiskBw() {
        
        diskBw_ = 0L;
        onChanged();
        return this;
      }

      private long netRxBw_ ;
      /**
       * <pre>
       * Network stats in KB
       * </pre>
       *
       * <code>optional int64 net_rx_bw = 9;</code>
       */
      public long getNetRxBw() {
        return netRxBw_;
      }
      /**
       * <pre>
       * Network stats in KB
       * </pre>
       *
       * <code>optional int64 net_rx_bw = 9;</code>
       */
      public Builder setNetRxBw(long value) {
        
        netRxBw_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Network stats in KB
       * </pre>
       *
       * <code>optional int64 net_rx_bw = 9;</code>
       */
      public Builder clearNetRxBw() {
        
        netRxBw_ = 0L;
        onChanged();
        return this;
      }

      private long netTxBw_ ;
      /**
       * <code>optional int64 net_tx_bw = 10;</code>
       */
      public long getNetTxBw() {
        return netTxBw_;
      }
      /**
       * <code>optional int64 net_tx_bw = 10;</code>
       */
      public Builder setNetTxBw(long value) {
        
        netTxBw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 net_tx_bw = 10;</code>
       */
      public Builder clearNetTxBw() {
        
        netTxBw_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:firmament.ResourceStats)
    }

    // @@protoc_insertion_point(class_scope:firmament.ResourceStats)
    private static final firmament.ResourceStatsOuterClass.ResourceStats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new firmament.ResourceStatsOuterClass.ResourceStats();
    }

    public static firmament.ResourceStatsOuterClass.ResourceStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResourceStats>
        PARSER = new com.google.protobuf.AbstractParser<ResourceStats>() {
      public ResourceStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResourceStats(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResourceStats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResourceStats> getParserForType() {
      return PARSER;
    }

    public firmament.ResourceStatsOuterClass.ResourceStats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CpuStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:firmament.CpuStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * CPU stats in millicores.
     * </pre>
     *
     * <code>optional int64 cpu_allocatable = 1;</code>
     */
    long getCpuAllocatable();

    /**
     * <code>optional int64 cpu_capacity = 2;</code>
     */
    long getCpuCapacity();

    /**
     * <pre>
     * CPU stats (fraction of total).
     * </pre>
     *
     * <code>optional double cpu_reservation = 3;</code>
     */
    double getCpuReservation();

    /**
     * <code>optional double cpu_utilization = 4;</code>
     */
    double getCpuUtilization();
  }
  /**
   * Protobuf type {@code firmament.CpuStats}
   */
  public  static final class CpuStats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:firmament.CpuStats)
      CpuStatsOrBuilder {
    // Use CpuStats.newBuilder() to construct.
    private CpuStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CpuStats() {
      cpuAllocatable_ = 0L;
      cpuCapacity_ = 0L;
      cpuReservation_ = 0D;
      cpuUtilization_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CpuStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cpuAllocatable_ = input.readInt64();
              break;
            }
            case 16: {

              cpuCapacity_ = input.readInt64();
              break;
            }
            case 25: {

              cpuReservation_ = input.readDouble();
              break;
            }
            case 33: {

              cpuUtilization_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return firmament.ResourceStatsOuterClass.internal_static_firmament_CpuStats_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return firmament.ResourceStatsOuterClass.internal_static_firmament_CpuStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              firmament.ResourceStatsOuterClass.CpuStats.class, firmament.ResourceStatsOuterClass.CpuStats.Builder.class);
    }

    public static final int CPU_ALLOCATABLE_FIELD_NUMBER = 1;
    private long cpuAllocatable_;
    /**
     * <pre>
     * CPU stats in millicores.
     * </pre>
     *
     * <code>optional int64 cpu_allocatable = 1;</code>
     */
    public long getCpuAllocatable() {
      return cpuAllocatable_;
    }

    public static final int CPU_CAPACITY_FIELD_NUMBER = 2;
    private long cpuCapacity_;
    /**
     * <code>optional int64 cpu_capacity = 2;</code>
     */
    public long getCpuCapacity() {
      return cpuCapacity_;
    }

    public static final int CPU_RESERVATION_FIELD_NUMBER = 3;
    private double cpuReservation_;
    /**
     * <pre>
     * CPU stats (fraction of total).
     * </pre>
     *
     * <code>optional double cpu_reservation = 3;</code>
     */
    public double getCpuReservation() {
      return cpuReservation_;
    }

    public static final int CPU_UTILIZATION_FIELD_NUMBER = 4;
    private double cpuUtilization_;
    /**
     * <code>optional double cpu_utilization = 4;</code>
     */
    public double getCpuUtilization() {
      return cpuUtilization_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cpuAllocatable_ != 0L) {
        output.writeInt64(1, cpuAllocatable_);
      }
      if (cpuCapacity_ != 0L) {
        output.writeInt64(2, cpuCapacity_);
      }
      if (cpuReservation_ != 0D) {
        output.writeDouble(3, cpuReservation_);
      }
      if (cpuUtilization_ != 0D) {
        output.writeDouble(4, cpuUtilization_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cpuAllocatable_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, cpuAllocatable_);
      }
      if (cpuCapacity_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cpuCapacity_);
      }
      if (cpuReservation_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, cpuReservation_);
      }
      if (cpuUtilization_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, cpuUtilization_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof firmament.ResourceStatsOuterClass.CpuStats)) {
        return super.equals(obj);
      }
      firmament.ResourceStatsOuterClass.CpuStats other = (firmament.ResourceStatsOuterClass.CpuStats) obj;

      boolean result = true;
      result = result && (getCpuAllocatable()
          == other.getCpuAllocatable());
      result = result && (getCpuCapacity()
          == other.getCpuCapacity());
      result = result && (
          java.lang.Double.doubleToLongBits(getCpuReservation())
          == java.lang.Double.doubleToLongBits(
              other.getCpuReservation()));
      result = result && (
          java.lang.Double.doubleToLongBits(getCpuUtilization())
          == java.lang.Double.doubleToLongBits(
              other.getCpuUtilization()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CPU_ALLOCATABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpuAllocatable());
      hash = (37 * hash) + CPU_CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpuCapacity());
      hash = (37 * hash) + CPU_RESERVATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCpuReservation()));
      hash = (37 * hash) + CPU_UTILIZATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCpuUtilization()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.ResourceStatsOuterClass.CpuStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(firmament.ResourceStatsOuterClass.CpuStats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code firmament.CpuStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:firmament.CpuStats)
        firmament.ResourceStatsOuterClass.CpuStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return firmament.ResourceStatsOuterClass.internal_static_firmament_CpuStats_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return firmament.ResourceStatsOuterClass.internal_static_firmament_CpuStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                firmament.ResourceStatsOuterClass.CpuStats.class, firmament.ResourceStatsOuterClass.CpuStats.Builder.class);
      }

      // Construct using firmament.ResourceStatsOuterClass.CpuStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cpuAllocatable_ = 0L;

        cpuCapacity_ = 0L;

        cpuReservation_ = 0D;

        cpuUtilization_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return firmament.ResourceStatsOuterClass.internal_static_firmament_CpuStats_descriptor;
      }

      public firmament.ResourceStatsOuterClass.CpuStats getDefaultInstanceForType() {
        return firmament.ResourceStatsOuterClass.CpuStats.getDefaultInstance();
      }

      public firmament.ResourceStatsOuterClass.CpuStats build() {
        firmament.ResourceStatsOuterClass.CpuStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public firmament.ResourceStatsOuterClass.CpuStats buildPartial() {
        firmament.ResourceStatsOuterClass.CpuStats result = new firmament.ResourceStatsOuterClass.CpuStats(this);
        result.cpuAllocatable_ = cpuAllocatable_;
        result.cpuCapacity_ = cpuCapacity_;
        result.cpuReservation_ = cpuReservation_;
        result.cpuUtilization_ = cpuUtilization_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof firmament.ResourceStatsOuterClass.CpuStats) {
          return mergeFrom((firmament.ResourceStatsOuterClass.CpuStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(firmament.ResourceStatsOuterClass.CpuStats other) {
        if (other == firmament.ResourceStatsOuterClass.CpuStats.getDefaultInstance()) return this;
        if (other.getCpuAllocatable() != 0L) {
          setCpuAllocatable(other.getCpuAllocatable());
        }
        if (other.getCpuCapacity() != 0L) {
          setCpuCapacity(other.getCpuCapacity());
        }
        if (other.getCpuReservation() != 0D) {
          setCpuReservation(other.getCpuReservation());
        }
        if (other.getCpuUtilization() != 0D) {
          setCpuUtilization(other.getCpuUtilization());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        firmament.ResourceStatsOuterClass.CpuStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (firmament.ResourceStatsOuterClass.CpuStats) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long cpuAllocatable_ ;
      /**
       * <pre>
       * CPU stats in millicores.
       * </pre>
       *
       * <code>optional int64 cpu_allocatable = 1;</code>
       */
      public long getCpuAllocatable() {
        return cpuAllocatable_;
      }
      /**
       * <pre>
       * CPU stats in millicores.
       * </pre>
       *
       * <code>optional int64 cpu_allocatable = 1;</code>
       */
      public Builder setCpuAllocatable(long value) {
        
        cpuAllocatable_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CPU stats in millicores.
       * </pre>
       *
       * <code>optional int64 cpu_allocatable = 1;</code>
       */
      public Builder clearCpuAllocatable() {
        
        cpuAllocatable_ = 0L;
        onChanged();
        return this;
      }

      private long cpuCapacity_ ;
      /**
       * <code>optional int64 cpu_capacity = 2;</code>
       */
      public long getCpuCapacity() {
        return cpuCapacity_;
      }
      /**
       * <code>optional int64 cpu_capacity = 2;</code>
       */
      public Builder setCpuCapacity(long value) {
        
        cpuCapacity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cpu_capacity = 2;</code>
       */
      public Builder clearCpuCapacity() {
        
        cpuCapacity_ = 0L;
        onChanged();
        return this;
      }

      private double cpuReservation_ ;
      /**
       * <pre>
       * CPU stats (fraction of total).
       * </pre>
       *
       * <code>optional double cpu_reservation = 3;</code>
       */
      public double getCpuReservation() {
        return cpuReservation_;
      }
      /**
       * <pre>
       * CPU stats (fraction of total).
       * </pre>
       *
       * <code>optional double cpu_reservation = 3;</code>
       */
      public Builder setCpuReservation(double value) {
        
        cpuReservation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CPU stats (fraction of total).
       * </pre>
       *
       * <code>optional double cpu_reservation = 3;</code>
       */
      public Builder clearCpuReservation() {
        
        cpuReservation_ = 0D;
        onChanged();
        return this;
      }

      private double cpuUtilization_ ;
      /**
       * <code>optional double cpu_utilization = 4;</code>
       */
      public double getCpuUtilization() {
        return cpuUtilization_;
      }
      /**
       * <code>optional double cpu_utilization = 4;</code>
       */
      public Builder setCpuUtilization(double value) {
        
        cpuUtilization_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double cpu_utilization = 4;</code>
       */
      public Builder clearCpuUtilization() {
        
        cpuUtilization_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:firmament.CpuStats)
    }

    // @@protoc_insertion_point(class_scope:firmament.CpuStats)
    private static final firmament.ResourceStatsOuterClass.CpuStats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new firmament.ResourceStatsOuterClass.CpuStats();
    }

    public static firmament.ResourceStatsOuterClass.CpuStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CpuStats>
        PARSER = new com.google.protobuf.AbstractParser<CpuStats>() {
      public CpuStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CpuStats(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CpuStats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CpuStats> getParserForType() {
      return PARSER;
    }

    public firmament.ResourceStatsOuterClass.CpuStats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firmament_ResourceStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firmament_ResourceStats_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firmament_CpuStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firmament_CpuStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024resource_stats.proto\022\tfirmament\"\370\001\n\rRe" +
      "sourceStats\022\023\n\013resource_id\030\001 \001(\t\022\021\n\ttime" +
      "stamp\030\002 \001(\004\022\'\n\ncpus_stats\030\003 \003(\0132\023.firmam" +
      "ent.CpuStats\022\027\n\017mem_allocatable\030\004 \001(\003\022\024\n" +
      "\014mem_capacity\030\005 \001(\003\022\027\n\017mem_reservation\030\006" +
      " \001(\001\022\027\n\017mem_utilization\030\007 \001(\001\022\017\n\007disk_bw" +
      "\030\010 \001(\003\022\021\n\tnet_rx_bw\030\t \001(\003\022\021\n\tnet_tx_bw\030\n" +
      " \001(\003\"k\n\010CpuStats\022\027\n\017cpu_allocatable\030\001 \001(" +
      "\003\022\024\n\014cpu_capacity\030\002 \001(\003\022\027\n\017cpu_reservati" +
      "on\030\003 \001(\001\022\027\n\017cpu_utilization\030\004 \001(\001b\006proto",
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_firmament_ResourceStats_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_firmament_ResourceStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firmament_ResourceStats_descriptor,
        new java.lang.String[] { "ResourceId", "Timestamp", "CpusStats", "MemAllocatable", "MemCapacity", "MemReservation", "MemUtilization", "DiskBw", "NetRxBw", "NetTxBw", });
    internal_static_firmament_CpuStats_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_firmament_CpuStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firmament_CpuStats_descriptor,
        new java.lang.String[] { "CpuAllocatable", "CpuCapacity", "CpuReservation", "CpuUtilization", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
