// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_topology_node_desc.proto

package firmament;

public final class ResourceTopologyNodeDesc {
  private ResourceTopologyNodeDesc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResourceTopologyNodeDescriptorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:firmament.ResourceTopologyNodeDescriptor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
     */
    boolean hasResourceDesc();
    /**
     * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
     */
    firmament.ResourceDesc.ResourceDescriptor getResourceDesc();
    /**
     * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
     */
    firmament.ResourceDesc.ResourceDescriptorOrBuilder getResourceDescOrBuilder();

    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    java.util.List<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor> 
        getChildrenList();
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor getChildren(int index);
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    java.util.List<? extends firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder> 
        getChildrenOrBuilderList();
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder getChildrenOrBuilder(
        int index);

    /**
     * <code>optional string parent_id = 3;</code>
     */
    java.lang.String getParentId();
    /**
     * <code>optional string parent_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getParentIdBytes();
  }
  /**
   * Protobuf type {@code firmament.ResourceTopologyNodeDescriptor}
   */
  public  static final class ResourceTopologyNodeDescriptor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:firmament.ResourceTopologyNodeDescriptor)
      ResourceTopologyNodeDescriptorOrBuilder {
    // Use ResourceTopologyNodeDescriptor.newBuilder() to construct.
    private ResourceTopologyNodeDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResourceTopologyNodeDescriptor() {
      children_ = java.util.Collections.emptyList();
      parentId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResourceTopologyNodeDescriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              firmament.ResourceDesc.ResourceDescriptor.Builder subBuilder = null;
              if (resourceDesc_ != null) {
                subBuilder = resourceDesc_.toBuilder();
              }
              resourceDesc_ = input.readMessage(firmament.ResourceDesc.ResourceDescriptor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resourceDesc_);
                resourceDesc_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                children_ = new java.util.ArrayList<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor>();
                mutable_bitField0_ |= 0x00000002;
              }
              children_.add(
                  input.readMessage(firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.parser(), extensionRegistry));
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              parentId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          children_ = java.util.Collections.unmodifiableList(children_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return firmament.ResourceTopologyNodeDesc.internal_static_firmament_ResourceTopologyNodeDescriptor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return firmament.ResourceTopologyNodeDesc.internal_static_firmament_ResourceTopologyNodeDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.class, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder.class);
    }

    private int bitField0_;
    public static final int RESOURCE_DESC_FIELD_NUMBER = 1;
    private firmament.ResourceDesc.ResourceDescriptor resourceDesc_;
    /**
     * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
     */
    public boolean hasResourceDesc() {
      return resourceDesc_ != null;
    }
    /**
     * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
     */
    public firmament.ResourceDesc.ResourceDescriptor getResourceDesc() {
      return resourceDesc_ == null ? firmament.ResourceDesc.ResourceDescriptor.getDefaultInstance() : resourceDesc_;
    }
    /**
     * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
     */
    public firmament.ResourceDesc.ResourceDescriptorOrBuilder getResourceDescOrBuilder() {
      return getResourceDesc();
    }

    public static final int CHILDREN_FIELD_NUMBER = 2;
    private java.util.List<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor> children_;
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    public java.util.List<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    public java.util.List<? extends firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder> 
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
     */
    public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    public static final int PARENT_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object parentId_;
    /**
     * <code>optional string parent_id = 3;</code>
     */
    public java.lang.String getParentId() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string parent_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resourceDesc_ != null) {
        output.writeMessage(1, getResourceDesc());
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(2, children_.get(i));
      }
      if (!getParentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parentId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resourceDesc_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResourceDesc());
      }
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, children_.get(i));
      }
      if (!getParentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, parentId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor)) {
        return super.equals(obj);
      }
      firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor other = (firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor) obj;

      boolean result = true;
      result = result && (hasResourceDesc() == other.hasResourceDesc());
      if (hasResourceDesc()) {
        result = result && getResourceDesc()
            .equals(other.getResourceDesc());
      }
      result = result && getChildrenList()
          .equals(other.getChildrenList());
      result = result && getParentId()
          .equals(other.getParentId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResourceDesc()) {
        hash = (37 * hash) + RESOURCE_DESC_FIELD_NUMBER;
        hash = (53 * hash) + getResourceDesc().hashCode();
      }
      if (getChildrenCount() > 0) {
        hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getChildrenList().hashCode();
      }
      hash = (37 * hash) + PARENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getParentId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code firmament.ResourceTopologyNodeDescriptor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:firmament.ResourceTopologyNodeDescriptor)
        firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return firmament.ResourceTopologyNodeDesc.internal_static_firmament_ResourceTopologyNodeDescriptor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return firmament.ResourceTopologyNodeDesc.internal_static_firmament_ResourceTopologyNodeDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.class, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder.class);
      }

      // Construct using firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChildrenFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (resourceDescBuilder_ == null) {
          resourceDesc_ = null;
        } else {
          resourceDesc_ = null;
          resourceDescBuilder_ = null;
        }
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          childrenBuilder_.clear();
        }
        parentId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return firmament.ResourceTopologyNodeDesc.internal_static_firmament_ResourceTopologyNodeDescriptor_descriptor;
      }

      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor getDefaultInstanceForType() {
        return firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.getDefaultInstance();
      }

      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor build() {
        firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor buildPartial() {
        firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor result = new firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (resourceDescBuilder_ == null) {
          result.resourceDesc_ = resourceDesc_;
        } else {
          result.resourceDesc_ = resourceDescBuilder_.build();
        }
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
        result.parentId_ = parentId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor) {
          return mergeFrom((firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor other) {
        if (other == firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.getDefaultInstance()) return this;
        if (other.hasResourceDesc()) {
          mergeResourceDesc(other.getResourceDesc());
        }
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000002);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        if (!other.getParentId().isEmpty()) {
          parentId_ = other.parentId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private firmament.ResourceDesc.ResourceDescriptor resourceDesc_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          firmament.ResourceDesc.ResourceDescriptor, firmament.ResourceDesc.ResourceDescriptor.Builder, firmament.ResourceDesc.ResourceDescriptorOrBuilder> resourceDescBuilder_;
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public boolean hasResourceDesc() {
        return resourceDescBuilder_ != null || resourceDesc_ != null;
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public firmament.ResourceDesc.ResourceDescriptor getResourceDesc() {
        if (resourceDescBuilder_ == null) {
          return resourceDesc_ == null ? firmament.ResourceDesc.ResourceDescriptor.getDefaultInstance() : resourceDesc_;
        } else {
          return resourceDescBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public Builder setResourceDesc(firmament.ResourceDesc.ResourceDescriptor value) {
        if (resourceDescBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resourceDesc_ = value;
          onChanged();
        } else {
          resourceDescBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public Builder setResourceDesc(
          firmament.ResourceDesc.ResourceDescriptor.Builder builderForValue) {
        if (resourceDescBuilder_ == null) {
          resourceDesc_ = builderForValue.build();
          onChanged();
        } else {
          resourceDescBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public Builder mergeResourceDesc(firmament.ResourceDesc.ResourceDescriptor value) {
        if (resourceDescBuilder_ == null) {
          if (resourceDesc_ != null) {
            resourceDesc_ =
              firmament.ResourceDesc.ResourceDescriptor.newBuilder(resourceDesc_).mergeFrom(value).buildPartial();
          } else {
            resourceDesc_ = value;
          }
          onChanged();
        } else {
          resourceDescBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public Builder clearResourceDesc() {
        if (resourceDescBuilder_ == null) {
          resourceDesc_ = null;
          onChanged();
        } else {
          resourceDesc_ = null;
          resourceDescBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public firmament.ResourceDesc.ResourceDescriptor.Builder getResourceDescBuilder() {
        
        onChanged();
        return getResourceDescFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      public firmament.ResourceDesc.ResourceDescriptorOrBuilder getResourceDescOrBuilder() {
        if (resourceDescBuilder_ != null) {
          return resourceDescBuilder_.getMessageOrBuilder();
        } else {
          return resourceDesc_ == null ?
              firmament.ResourceDesc.ResourceDescriptor.getDefaultInstance() : resourceDesc_;
        }
      }
      /**
       * <code>optional .firmament.ResourceDescriptor resource_desc = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          firmament.ResourceDesc.ResourceDescriptor, firmament.ResourceDesc.ResourceDescriptor.Builder, firmament.ResourceDesc.ResourceDescriptorOrBuilder> 
          getResourceDescFieldBuilder() {
        if (resourceDescBuilder_ == null) {
          resourceDescBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              firmament.ResourceDesc.ResourceDescriptor, firmament.ResourceDesc.ResourceDescriptor.Builder, firmament.ResourceDesc.ResourceDescriptorOrBuilder>(
                  getResourceDesc(),
                  getParentForChildren(),
                  isClean());
          resourceDesc_ = null;
        }
        return resourceDescBuilder_;
      }

      private java.util.List<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          children_ = new java.util.ArrayList<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor>(children_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder> childrenBuilder_;

      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public java.util.List<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder setChildren(
          int index, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder setChildren(
          int index, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder addChildren(firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder addChildren(
          int index, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder addChildren(
          firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder addChildren(
          int index, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<? extends firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder getChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public java.util.List<? extends firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder> 
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder addChildrenBuilder() {
        return getChildrenFieldBuilder().addBuilder(
            firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder addChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().addBuilder(
            index, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .firmament.ResourceTopologyNodeDescriptor children = 2;</code>
       */
      public java.util.List<firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder> 
           getChildrenBuilderList() {
        return getChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder> 
          getChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor.Builder, firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptorOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }

      private java.lang.Object parentId_ = "";
      /**
       * <code>optional string parent_id = 3;</code>
       */
      public java.lang.String getParentId() {
        java.lang.Object ref = parentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parent_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParentIdBytes() {
        java.lang.Object ref = parentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parent_id = 3;</code>
       */
      public Builder setParentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parent_id = 3;</code>
       */
      public Builder clearParentId() {
        
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parent_id = 3;</code>
       */
      public Builder setParentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parentId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:firmament.ResourceTopologyNodeDescriptor)
    }

    // @@protoc_insertion_point(class_scope:firmament.ResourceTopologyNodeDescriptor)
    private static final firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor();
    }

    public static firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResourceTopologyNodeDescriptor>
        PARSER = new com.google.protobuf.AbstractParser<ResourceTopologyNodeDescriptor>() {
      public ResourceTopologyNodeDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResourceTopologyNodeDescriptor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResourceTopologyNodeDescriptor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResourceTopologyNodeDescriptor> getParserForType() {
      return PARSER;
    }

    public firmament.ResourceTopologyNodeDesc.ResourceTopologyNodeDescriptor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firmament_ResourceTopologyNodeDescriptor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firmament_ResourceTopologyNodeDescriptor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!resource_topology_node_desc.proto\022\tfir" +
      "mament\032\023resource_desc.proto\"\246\001\n\036Resource" +
      "TopologyNodeDescriptor\0224\n\rresource_desc\030" +
      "\001 \001(\0132\035.firmament.ResourceDescriptor\022;\n\010" +
      "children\030\002 \003(\0132).firmament.ResourceTopol" +
      "ogyNodeDescriptor\022\021\n\tparent_id\030\003 \001(\tb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          firmament.ResourceDesc.getDescriptor(),
        }, assigner);
    internal_static_firmament_ResourceTopologyNodeDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_firmament_ResourceTopologyNodeDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firmament_ResourceTopologyNodeDescriptor_descriptor,
        new java.lang.String[] { "ResourceDesc", "Children", "ParentId", });
    firmament.ResourceDesc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
