// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/firmament/task_final_report.proto

package firmament;

public final class TaskFinalReportOuterClass {
  private TaskFinalReportOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskFinalReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:firmament.TaskFinalReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 task_id = 1;</code>
     */
    long getTaskId();

    /**
     * <code>optional uint64 start_time = 2;</code>
     */
    long getStartTime();

    /**
     * <code>optional uint64 finish_time = 3;</code>
     */
    long getFinishTime();

    /**
     * <code>optional uint64 instructions = 4;</code>
     */
    long getInstructions();

    /**
     * <code>optional uint64 cycles = 5;</code>
     */
    long getCycles();

    /**
     * <code>optional uint64 llc_refs = 6;</code>
     */
    long getLlcRefs();

    /**
     * <code>optional uint64 llc_misses = 7;</code>
     */
    long getLlcMisses();

    /**
     * <code>optional double runtime = 8;</code>
     */
    double getRuntime();
  }
  /**
   * Protobuf type {@code firmament.TaskFinalReport}
   */
  public  static final class TaskFinalReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:firmament.TaskFinalReport)
      TaskFinalReportOrBuilder {
    // Use TaskFinalReport.newBuilder() to construct.
    private TaskFinalReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskFinalReport() {
      taskId_ = 0L;
      startTime_ = 0L;
      finishTime_ = 0L;
      instructions_ = 0L;
      cycles_ = 0L;
      llcRefs_ = 0L;
      llcMisses_ = 0L;
      runtime_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TaskFinalReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              taskId_ = input.readUInt64();
              break;
            }
            case 16: {

              startTime_ = input.readUInt64();
              break;
            }
            case 24: {

              finishTime_ = input.readUInt64();
              break;
            }
            case 32: {

              instructions_ = input.readUInt64();
              break;
            }
            case 40: {

              cycles_ = input.readUInt64();
              break;
            }
            case 48: {

              llcRefs_ = input.readUInt64();
              break;
            }
            case 56: {

              llcMisses_ = input.readUInt64();
              break;
            }
            case 65: {

              runtime_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return firmament.TaskFinalReportOuterClass.internal_static_firmament_TaskFinalReport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return firmament.TaskFinalReportOuterClass.internal_static_firmament_TaskFinalReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              firmament.TaskFinalReportOuterClass.TaskFinalReport.class, firmament.TaskFinalReportOuterClass.TaskFinalReport.Builder.class);
    }

    public static final int TASK_ID_FIELD_NUMBER = 1;
    private long taskId_;
    /**
     * <code>optional uint64 task_id = 1;</code>
     */
    public long getTaskId() {
      return taskId_;
    }

    public static final int START_TIME_FIELD_NUMBER = 2;
    private long startTime_;
    /**
     * <code>optional uint64 start_time = 2;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int FINISH_TIME_FIELD_NUMBER = 3;
    private long finishTime_;
    /**
     * <code>optional uint64 finish_time = 3;</code>
     */
    public long getFinishTime() {
      return finishTime_;
    }

    public static final int INSTRUCTIONS_FIELD_NUMBER = 4;
    private long instructions_;
    /**
     * <code>optional uint64 instructions = 4;</code>
     */
    public long getInstructions() {
      return instructions_;
    }

    public static final int CYCLES_FIELD_NUMBER = 5;
    private long cycles_;
    /**
     * <code>optional uint64 cycles = 5;</code>
     */
    public long getCycles() {
      return cycles_;
    }

    public static final int LLC_REFS_FIELD_NUMBER = 6;
    private long llcRefs_;
    /**
     * <code>optional uint64 llc_refs = 6;</code>
     */
    public long getLlcRefs() {
      return llcRefs_;
    }

    public static final int LLC_MISSES_FIELD_NUMBER = 7;
    private long llcMisses_;
    /**
     * <code>optional uint64 llc_misses = 7;</code>
     */
    public long getLlcMisses() {
      return llcMisses_;
    }

    public static final int RUNTIME_FIELD_NUMBER = 8;
    private double runtime_;
    /**
     * <code>optional double runtime = 8;</code>
     */
    public double getRuntime() {
      return runtime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (taskId_ != 0L) {
        output.writeUInt64(1, taskId_);
      }
      if (startTime_ != 0L) {
        output.writeUInt64(2, startTime_);
      }
      if (finishTime_ != 0L) {
        output.writeUInt64(3, finishTime_);
      }
      if (instructions_ != 0L) {
        output.writeUInt64(4, instructions_);
      }
      if (cycles_ != 0L) {
        output.writeUInt64(5, cycles_);
      }
      if (llcRefs_ != 0L) {
        output.writeUInt64(6, llcRefs_);
      }
      if (llcMisses_ != 0L) {
        output.writeUInt64(7, llcMisses_);
      }
      if (runtime_ != 0D) {
        output.writeDouble(8, runtime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (taskId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, taskId_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, startTime_);
      }
      if (finishTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, finishTime_);
      }
      if (instructions_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, instructions_);
      }
      if (cycles_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, cycles_);
      }
      if (llcRefs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, llcRefs_);
      }
      if (llcMisses_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, llcMisses_);
      }
      if (runtime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, runtime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof firmament.TaskFinalReportOuterClass.TaskFinalReport)) {
        return super.equals(obj);
      }
      firmament.TaskFinalReportOuterClass.TaskFinalReport other = (firmament.TaskFinalReportOuterClass.TaskFinalReport) obj;

      boolean result = true;
      result = result && (getTaskId()
          == other.getTaskId());
      result = result && (getStartTime()
          == other.getStartTime());
      result = result && (getFinishTime()
          == other.getFinishTime());
      result = result && (getInstructions()
          == other.getInstructions());
      result = result && (getCycles()
          == other.getCycles());
      result = result && (getLlcRefs()
          == other.getLlcRefs());
      result = result && (getLlcMisses()
          == other.getLlcMisses());
      result = result && (
          java.lang.Double.doubleToLongBits(getRuntime())
          == java.lang.Double.doubleToLongBits(
              other.getRuntime()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskId());
      hash = (37 * hash) + START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + FINISH_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFinishTime());
      hash = (37 * hash) + INSTRUCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInstructions());
      hash = (37 * hash) + CYCLES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCycles());
      hash = (37 * hash) + LLC_REFS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLlcRefs());
      hash = (37 * hash) + LLC_MISSES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLlcMisses());
      hash = (37 * hash) + RUNTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRuntime()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.TaskFinalReportOuterClass.TaskFinalReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(firmament.TaskFinalReportOuterClass.TaskFinalReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code firmament.TaskFinalReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:firmament.TaskFinalReport)
        firmament.TaskFinalReportOuterClass.TaskFinalReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return firmament.TaskFinalReportOuterClass.internal_static_firmament_TaskFinalReport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return firmament.TaskFinalReportOuterClass.internal_static_firmament_TaskFinalReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                firmament.TaskFinalReportOuterClass.TaskFinalReport.class, firmament.TaskFinalReportOuterClass.TaskFinalReport.Builder.class);
      }

      // Construct using firmament.TaskFinalReportOuterClass.TaskFinalReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskId_ = 0L;

        startTime_ = 0L;

        finishTime_ = 0L;

        instructions_ = 0L;

        cycles_ = 0L;

        llcRefs_ = 0L;

        llcMisses_ = 0L;

        runtime_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return firmament.TaskFinalReportOuterClass.internal_static_firmament_TaskFinalReport_descriptor;
      }

      public firmament.TaskFinalReportOuterClass.TaskFinalReport getDefaultInstanceForType() {
        return firmament.TaskFinalReportOuterClass.TaskFinalReport.getDefaultInstance();
      }

      public firmament.TaskFinalReportOuterClass.TaskFinalReport build() {
        firmament.TaskFinalReportOuterClass.TaskFinalReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public firmament.TaskFinalReportOuterClass.TaskFinalReport buildPartial() {
        firmament.TaskFinalReportOuterClass.TaskFinalReport result = new firmament.TaskFinalReportOuterClass.TaskFinalReport(this);
        result.taskId_ = taskId_;
        result.startTime_ = startTime_;
        result.finishTime_ = finishTime_;
        result.instructions_ = instructions_;
        result.cycles_ = cycles_;
        result.llcRefs_ = llcRefs_;
        result.llcMisses_ = llcMisses_;
        result.runtime_ = runtime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof firmament.TaskFinalReportOuterClass.TaskFinalReport) {
          return mergeFrom((firmament.TaskFinalReportOuterClass.TaskFinalReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(firmament.TaskFinalReportOuterClass.TaskFinalReport other) {
        if (other == firmament.TaskFinalReportOuterClass.TaskFinalReport.getDefaultInstance()) return this;
        if (other.getTaskId() != 0L) {
          setTaskId(other.getTaskId());
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getFinishTime() != 0L) {
          setFinishTime(other.getFinishTime());
        }
        if (other.getInstructions() != 0L) {
          setInstructions(other.getInstructions());
        }
        if (other.getCycles() != 0L) {
          setCycles(other.getCycles());
        }
        if (other.getLlcRefs() != 0L) {
          setLlcRefs(other.getLlcRefs());
        }
        if (other.getLlcMisses() != 0L) {
          setLlcMisses(other.getLlcMisses());
        }
        if (other.getRuntime() != 0D) {
          setRuntime(other.getRuntime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        firmament.TaskFinalReportOuterClass.TaskFinalReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (firmament.TaskFinalReportOuterClass.TaskFinalReport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long taskId_ ;
      /**
       * <code>optional uint64 task_id = 1;</code>
       */
      public long getTaskId() {
        return taskId_;
      }
      /**
       * <code>optional uint64 task_id = 1;</code>
       */
      public Builder setTaskId(long value) {
        
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 task_id = 1;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = 0L;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>optional uint64 start_time = 2;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>optional uint64 start_time = 2;</code>
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 start_time = 2;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long finishTime_ ;
      /**
       * <code>optional uint64 finish_time = 3;</code>
       */
      public long getFinishTime() {
        return finishTime_;
      }
      /**
       * <code>optional uint64 finish_time = 3;</code>
       */
      public Builder setFinishTime(long value) {
        
        finishTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 finish_time = 3;</code>
       */
      public Builder clearFinishTime() {
        
        finishTime_ = 0L;
        onChanged();
        return this;
      }

      private long instructions_ ;
      /**
       * <code>optional uint64 instructions = 4;</code>
       */
      public long getInstructions() {
        return instructions_;
      }
      /**
       * <code>optional uint64 instructions = 4;</code>
       */
      public Builder setInstructions(long value) {
        
        instructions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 instructions = 4;</code>
       */
      public Builder clearInstructions() {
        
        instructions_ = 0L;
        onChanged();
        return this;
      }

      private long cycles_ ;
      /**
       * <code>optional uint64 cycles = 5;</code>
       */
      public long getCycles() {
        return cycles_;
      }
      /**
       * <code>optional uint64 cycles = 5;</code>
       */
      public Builder setCycles(long value) {
        
        cycles_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 cycles = 5;</code>
       */
      public Builder clearCycles() {
        
        cycles_ = 0L;
        onChanged();
        return this;
      }

      private long llcRefs_ ;
      /**
       * <code>optional uint64 llc_refs = 6;</code>
       */
      public long getLlcRefs() {
        return llcRefs_;
      }
      /**
       * <code>optional uint64 llc_refs = 6;</code>
       */
      public Builder setLlcRefs(long value) {
        
        llcRefs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 llc_refs = 6;</code>
       */
      public Builder clearLlcRefs() {
        
        llcRefs_ = 0L;
        onChanged();
        return this;
      }

      private long llcMisses_ ;
      /**
       * <code>optional uint64 llc_misses = 7;</code>
       */
      public long getLlcMisses() {
        return llcMisses_;
      }
      /**
       * <code>optional uint64 llc_misses = 7;</code>
       */
      public Builder setLlcMisses(long value) {
        
        llcMisses_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 llc_misses = 7;</code>
       */
      public Builder clearLlcMisses() {
        
        llcMisses_ = 0L;
        onChanged();
        return this;
      }

      private double runtime_ ;
      /**
       * <code>optional double runtime = 8;</code>
       */
      public double getRuntime() {
        return runtime_;
      }
      /**
       * <code>optional double runtime = 8;</code>
       */
      public Builder setRuntime(double value) {
        
        runtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double runtime = 8;</code>
       */
      public Builder clearRuntime() {
        
        runtime_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:firmament.TaskFinalReport)
    }

    // @@protoc_insertion_point(class_scope:firmament.TaskFinalReport)
    private static final firmament.TaskFinalReportOuterClass.TaskFinalReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new firmament.TaskFinalReportOuterClass.TaskFinalReport();
    }

    public static firmament.TaskFinalReportOuterClass.TaskFinalReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskFinalReport>
        PARSER = new com.google.protobuf.AbstractParser<TaskFinalReport>() {
      public TaskFinalReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TaskFinalReport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskFinalReport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskFinalReport> getParserForType() {
      return PARSER;
    }

    public firmament.TaskFinalReportOuterClass.TaskFinalReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firmament_TaskFinalReport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firmament_TaskFinalReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3src/main/protobuf/firmament/task_final" +
      "_report.proto\022\tfirmament\"\250\001\n\017TaskFinalRe" +
      "port\022\017\n\007task_id\030\001 \001(\004\022\022\n\nstart_time\030\002 \001(" +
      "\004\022\023\n\013finish_time\030\003 \001(\004\022\024\n\014instructions\030\004" +
      " \001(\004\022\016\n\006cycles\030\005 \001(\004\022\020\n\010llc_refs\030\006 \001(\004\022\022" +
      "\n\nllc_misses\030\007 \001(\004\022\017\n\007runtime\030\010 \001(\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_firmament_TaskFinalReport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_firmament_TaskFinalReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firmament_TaskFinalReport_descriptor,
        new java.lang.String[] { "TaskId", "StartTime", "FinishTime", "Instructions", "Cycles", "LlcRefs", "LlcMisses", "Runtime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
