// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_stats.proto

package firmament;

public final class TaskStatsOuterClass {
  private TaskStatsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:firmament.TaskStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 task_id = 1;</code>
     */
    long getTaskId();

    /**
     * <code>optional string hostname = 2;</code>
     */
    java.lang.String getHostname();
    /**
     * <code>optional string hostname = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostnameBytes();

    /**
     * <code>optional uint64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     * CPU stats in millicores.
     * </pre>
     *
     * <code>optional int64 cpu_limit = 4;</code>
     */
    long getCpuLimit();

    /**
     * <code>optional int64 cpu_request = 5;</code>
     */
    long getCpuRequest();

    /**
     * <code>optional int64 cpu_usage = 6;</code>
     */
    long getCpuUsage();

    /**
     * <pre>
     * Memory stats in Kb.
     * </pre>
     *
     * <code>optional int64 mem_limit = 7;</code>
     */
    long getMemLimit();

    /**
     * <code>optional int64 mem_request = 8;</code>
     */
    long getMemRequest();

    /**
     * <code>optional int64 mem_usage = 9;</code>
     */
    long getMemUsage();

    /**
     * <code>optional int64 mem_rss = 10;</code>
     */
    long getMemRss();

    /**
     * <code>optional int64 mem_cache = 11;</code>
     */
    long getMemCache();

    /**
     * <code>optional int64 mem_working_set = 12;</code>
     */
    long getMemWorkingSet();

    /**
     * <code>optional int64 mem_page_faults = 13;</code>
     */
    long getMemPageFaults();

    /**
     * <code>optional double mem_page_faults_rate = 14;</code>
     */
    double getMemPageFaultsRate();

    /**
     * <code>optional int64 major_page_faults = 15;</code>
     */
    long getMajorPageFaults();

    /**
     * <code>optional double major_page_faults_rate = 16;</code>
     */
    double getMajorPageFaultsRate();

    /**
     * <pre>
     * Network stats in Kb.
     * </pre>
     *
     * <code>optional int64 net_rx = 17;</code>
     */
    long getNetRx();

    /**
     * <code>optional int64 net_rx_errors = 18;</code>
     */
    long getNetRxErrors();

    /**
     * <code>optional double net_rx_errors_rate = 19;</code>
     */
    double getNetRxErrorsRate();

    /**
     * <code>optional double net_rx_rate = 20;</code>
     */
    double getNetRxRate();

    /**
     * <code>optional int64 net_tx = 21;</code>
     */
    long getNetTx();

    /**
     * <code>optional int64 net_tx_errors = 22;</code>
     */
    long getNetTxErrors();

    /**
     * <code>optional double net_tx_errors_rate = 23;</code>
     */
    double getNetTxErrorsRate();

    /**
     * <code>optional double net_tx_rate = 24;</code>
     */
    double getNetTxRate();
  }
  /**
   * Protobuf type {@code firmament.TaskStats}
   */
  public  static final class TaskStats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:firmament.TaskStats)
      TaskStatsOrBuilder {
    // Use TaskStats.newBuilder() to construct.
    private TaskStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskStats() {
      taskId_ = 0L;
      hostname_ = "";
      timestamp_ = 0L;
      cpuLimit_ = 0L;
      cpuRequest_ = 0L;
      cpuUsage_ = 0L;
      memLimit_ = 0L;
      memRequest_ = 0L;
      memUsage_ = 0L;
      memRss_ = 0L;
      memCache_ = 0L;
      memWorkingSet_ = 0L;
      memPageFaults_ = 0L;
      memPageFaultsRate_ = 0D;
      majorPageFaults_ = 0L;
      majorPageFaultsRate_ = 0D;
      netRx_ = 0L;
      netRxErrors_ = 0L;
      netRxErrorsRate_ = 0D;
      netRxRate_ = 0D;
      netTx_ = 0L;
      netTxErrors_ = 0L;
      netTxErrorsRate_ = 0D;
      netTxRate_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TaskStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              taskId_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hostname_ = s;
              break;
            }
            case 24: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 32: {

              cpuLimit_ = input.readInt64();
              break;
            }
            case 40: {

              cpuRequest_ = input.readInt64();
              break;
            }
            case 48: {

              cpuUsage_ = input.readInt64();
              break;
            }
            case 56: {

              memLimit_ = input.readInt64();
              break;
            }
            case 64: {

              memRequest_ = input.readInt64();
              break;
            }
            case 72: {

              memUsage_ = input.readInt64();
              break;
            }
            case 80: {

              memRss_ = input.readInt64();
              break;
            }
            case 88: {

              memCache_ = input.readInt64();
              break;
            }
            case 96: {

              memWorkingSet_ = input.readInt64();
              break;
            }
            case 104: {

              memPageFaults_ = input.readInt64();
              break;
            }
            case 113: {

              memPageFaultsRate_ = input.readDouble();
              break;
            }
            case 120: {

              majorPageFaults_ = input.readInt64();
              break;
            }
            case 129: {

              majorPageFaultsRate_ = input.readDouble();
              break;
            }
            case 136: {

              netRx_ = input.readInt64();
              break;
            }
            case 144: {

              netRxErrors_ = input.readInt64();
              break;
            }
            case 153: {

              netRxErrorsRate_ = input.readDouble();
              break;
            }
            case 161: {

              netRxRate_ = input.readDouble();
              break;
            }
            case 168: {

              netTx_ = input.readInt64();
              break;
            }
            case 176: {

              netTxErrors_ = input.readInt64();
              break;
            }
            case 185: {

              netTxErrorsRate_ = input.readDouble();
              break;
            }
            case 193: {

              netTxRate_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return firmament.TaskStatsOuterClass.internal_static_firmament_TaskStats_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return firmament.TaskStatsOuterClass.internal_static_firmament_TaskStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              firmament.TaskStatsOuterClass.TaskStats.class, firmament.TaskStatsOuterClass.TaskStats.Builder.class);
    }

    public static final int TASK_ID_FIELD_NUMBER = 1;
    private long taskId_;
    /**
     * <code>optional uint64 task_id = 1;</code>
     */
    public long getTaskId() {
      return taskId_;
    }

    public static final int HOSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object hostname_;
    /**
     * <code>optional string hostname = 2;</code>
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hostname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CPU_LIMIT_FIELD_NUMBER = 4;
    private long cpuLimit_;
    /**
     * <pre>
     * CPU stats in millicores.
     * </pre>
     *
     * <code>optional int64 cpu_limit = 4;</code>
     */
    public long getCpuLimit() {
      return cpuLimit_;
    }

    public static final int CPU_REQUEST_FIELD_NUMBER = 5;
    private long cpuRequest_;
    /**
     * <code>optional int64 cpu_request = 5;</code>
     */
    public long getCpuRequest() {
      return cpuRequest_;
    }

    public static final int CPU_USAGE_FIELD_NUMBER = 6;
    private long cpuUsage_;
    /**
     * <code>optional int64 cpu_usage = 6;</code>
     */
    public long getCpuUsage() {
      return cpuUsage_;
    }

    public static final int MEM_LIMIT_FIELD_NUMBER = 7;
    private long memLimit_;
    /**
     * <pre>
     * Memory stats in Kb.
     * </pre>
     *
     * <code>optional int64 mem_limit = 7;</code>
     */
    public long getMemLimit() {
      return memLimit_;
    }

    public static final int MEM_REQUEST_FIELD_NUMBER = 8;
    private long memRequest_;
    /**
     * <code>optional int64 mem_request = 8;</code>
     */
    public long getMemRequest() {
      return memRequest_;
    }

    public static final int MEM_USAGE_FIELD_NUMBER = 9;
    private long memUsage_;
    /**
     * <code>optional int64 mem_usage = 9;</code>
     */
    public long getMemUsage() {
      return memUsage_;
    }

    public static final int MEM_RSS_FIELD_NUMBER = 10;
    private long memRss_;
    /**
     * <code>optional int64 mem_rss = 10;</code>
     */
    public long getMemRss() {
      return memRss_;
    }

    public static final int MEM_CACHE_FIELD_NUMBER = 11;
    private long memCache_;
    /**
     * <code>optional int64 mem_cache = 11;</code>
     */
    public long getMemCache() {
      return memCache_;
    }

    public static final int MEM_WORKING_SET_FIELD_NUMBER = 12;
    private long memWorkingSet_;
    /**
     * <code>optional int64 mem_working_set = 12;</code>
     */
    public long getMemWorkingSet() {
      return memWorkingSet_;
    }

    public static final int MEM_PAGE_FAULTS_FIELD_NUMBER = 13;
    private long memPageFaults_;
    /**
     * <code>optional int64 mem_page_faults = 13;</code>
     */
    public long getMemPageFaults() {
      return memPageFaults_;
    }

    public static final int MEM_PAGE_FAULTS_RATE_FIELD_NUMBER = 14;
    private double memPageFaultsRate_;
    /**
     * <code>optional double mem_page_faults_rate = 14;</code>
     */
    public double getMemPageFaultsRate() {
      return memPageFaultsRate_;
    }

    public static final int MAJOR_PAGE_FAULTS_FIELD_NUMBER = 15;
    private long majorPageFaults_;
    /**
     * <code>optional int64 major_page_faults = 15;</code>
     */
    public long getMajorPageFaults() {
      return majorPageFaults_;
    }

    public static final int MAJOR_PAGE_FAULTS_RATE_FIELD_NUMBER = 16;
    private double majorPageFaultsRate_;
    /**
     * <code>optional double major_page_faults_rate = 16;</code>
     */
    public double getMajorPageFaultsRate() {
      return majorPageFaultsRate_;
    }

    public static final int NET_RX_FIELD_NUMBER = 17;
    private long netRx_;
    /**
     * <pre>
     * Network stats in Kb.
     * </pre>
     *
     * <code>optional int64 net_rx = 17;</code>
     */
    public long getNetRx() {
      return netRx_;
    }

    public static final int NET_RX_ERRORS_FIELD_NUMBER = 18;
    private long netRxErrors_;
    /**
     * <code>optional int64 net_rx_errors = 18;</code>
     */
    public long getNetRxErrors() {
      return netRxErrors_;
    }

    public static final int NET_RX_ERRORS_RATE_FIELD_NUMBER = 19;
    private double netRxErrorsRate_;
    /**
     * <code>optional double net_rx_errors_rate = 19;</code>
     */
    public double getNetRxErrorsRate() {
      return netRxErrorsRate_;
    }

    public static final int NET_RX_RATE_FIELD_NUMBER = 20;
    private double netRxRate_;
    /**
     * <code>optional double net_rx_rate = 20;</code>
     */
    public double getNetRxRate() {
      return netRxRate_;
    }

    public static final int NET_TX_FIELD_NUMBER = 21;
    private long netTx_;
    /**
     * <code>optional int64 net_tx = 21;</code>
     */
    public long getNetTx() {
      return netTx_;
    }

    public static final int NET_TX_ERRORS_FIELD_NUMBER = 22;
    private long netTxErrors_;
    /**
     * <code>optional int64 net_tx_errors = 22;</code>
     */
    public long getNetTxErrors() {
      return netTxErrors_;
    }

    public static final int NET_TX_ERRORS_RATE_FIELD_NUMBER = 23;
    private double netTxErrorsRate_;
    /**
     * <code>optional double net_tx_errors_rate = 23;</code>
     */
    public double getNetTxErrorsRate() {
      return netTxErrorsRate_;
    }

    public static final int NET_TX_RATE_FIELD_NUMBER = 24;
    private double netTxRate_;
    /**
     * <code>optional double net_tx_rate = 24;</code>
     */
    public double getNetTxRate() {
      return netTxRate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (taskId_ != 0L) {
        output.writeUInt64(1, taskId_);
      }
      if (!getHostnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hostname_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(3, timestamp_);
      }
      if (cpuLimit_ != 0L) {
        output.writeInt64(4, cpuLimit_);
      }
      if (cpuRequest_ != 0L) {
        output.writeInt64(5, cpuRequest_);
      }
      if (cpuUsage_ != 0L) {
        output.writeInt64(6, cpuUsage_);
      }
      if (memLimit_ != 0L) {
        output.writeInt64(7, memLimit_);
      }
      if (memRequest_ != 0L) {
        output.writeInt64(8, memRequest_);
      }
      if (memUsage_ != 0L) {
        output.writeInt64(9, memUsage_);
      }
      if (memRss_ != 0L) {
        output.writeInt64(10, memRss_);
      }
      if (memCache_ != 0L) {
        output.writeInt64(11, memCache_);
      }
      if (memWorkingSet_ != 0L) {
        output.writeInt64(12, memWorkingSet_);
      }
      if (memPageFaults_ != 0L) {
        output.writeInt64(13, memPageFaults_);
      }
      if (memPageFaultsRate_ != 0D) {
        output.writeDouble(14, memPageFaultsRate_);
      }
      if (majorPageFaults_ != 0L) {
        output.writeInt64(15, majorPageFaults_);
      }
      if (majorPageFaultsRate_ != 0D) {
        output.writeDouble(16, majorPageFaultsRate_);
      }
      if (netRx_ != 0L) {
        output.writeInt64(17, netRx_);
      }
      if (netRxErrors_ != 0L) {
        output.writeInt64(18, netRxErrors_);
      }
      if (netRxErrorsRate_ != 0D) {
        output.writeDouble(19, netRxErrorsRate_);
      }
      if (netRxRate_ != 0D) {
        output.writeDouble(20, netRxRate_);
      }
      if (netTx_ != 0L) {
        output.writeInt64(21, netTx_);
      }
      if (netTxErrors_ != 0L) {
        output.writeInt64(22, netTxErrors_);
      }
      if (netTxErrorsRate_ != 0D) {
        output.writeDouble(23, netTxErrorsRate_);
      }
      if (netTxRate_ != 0D) {
        output.writeDouble(24, netTxRate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (taskId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, taskId_);
      }
      if (!getHostnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hostname_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      if (cpuLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, cpuLimit_);
      }
      if (cpuRequest_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, cpuRequest_);
      }
      if (cpuUsage_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, cpuUsage_);
      }
      if (memLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, memLimit_);
      }
      if (memRequest_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, memRequest_);
      }
      if (memUsage_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, memUsage_);
      }
      if (memRss_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, memRss_);
      }
      if (memCache_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, memCache_);
      }
      if (memWorkingSet_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, memWorkingSet_);
      }
      if (memPageFaults_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, memPageFaults_);
      }
      if (memPageFaultsRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, memPageFaultsRate_);
      }
      if (majorPageFaults_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, majorPageFaults_);
      }
      if (majorPageFaultsRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(16, majorPageFaultsRate_);
      }
      if (netRx_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, netRx_);
      }
      if (netRxErrors_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(18, netRxErrors_);
      }
      if (netRxErrorsRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(19, netRxErrorsRate_);
      }
      if (netRxRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(20, netRxRate_);
      }
      if (netTx_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(21, netTx_);
      }
      if (netTxErrors_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(22, netTxErrors_);
      }
      if (netTxErrorsRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(23, netTxErrorsRate_);
      }
      if (netTxRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(24, netTxRate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof firmament.TaskStatsOuterClass.TaskStats)) {
        return super.equals(obj);
      }
      firmament.TaskStatsOuterClass.TaskStats other = (firmament.TaskStatsOuterClass.TaskStats) obj;

      boolean result = true;
      result = result && (getTaskId()
          == other.getTaskId());
      result = result && getHostname()
          .equals(other.getHostname());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && (getCpuLimit()
          == other.getCpuLimit());
      result = result && (getCpuRequest()
          == other.getCpuRequest());
      result = result && (getCpuUsage()
          == other.getCpuUsage());
      result = result && (getMemLimit()
          == other.getMemLimit());
      result = result && (getMemRequest()
          == other.getMemRequest());
      result = result && (getMemUsage()
          == other.getMemUsage());
      result = result && (getMemRss()
          == other.getMemRss());
      result = result && (getMemCache()
          == other.getMemCache());
      result = result && (getMemWorkingSet()
          == other.getMemWorkingSet());
      result = result && (getMemPageFaults()
          == other.getMemPageFaults());
      result = result && (
          java.lang.Double.doubleToLongBits(getMemPageFaultsRate())
          == java.lang.Double.doubleToLongBits(
              other.getMemPageFaultsRate()));
      result = result && (getMajorPageFaults()
          == other.getMajorPageFaults());
      result = result && (
          java.lang.Double.doubleToLongBits(getMajorPageFaultsRate())
          == java.lang.Double.doubleToLongBits(
              other.getMajorPageFaultsRate()));
      result = result && (getNetRx()
          == other.getNetRx());
      result = result && (getNetRxErrors()
          == other.getNetRxErrors());
      result = result && (
          java.lang.Double.doubleToLongBits(getNetRxErrorsRate())
          == java.lang.Double.doubleToLongBits(
              other.getNetRxErrorsRate()));
      result = result && (
          java.lang.Double.doubleToLongBits(getNetRxRate())
          == java.lang.Double.doubleToLongBits(
              other.getNetRxRate()));
      result = result && (getNetTx()
          == other.getNetTx());
      result = result && (getNetTxErrors()
          == other.getNetTxErrors());
      result = result && (
          java.lang.Double.doubleToLongBits(getNetTxErrorsRate())
          == java.lang.Double.doubleToLongBits(
              other.getNetTxErrorsRate()));
      result = result && (
          java.lang.Double.doubleToLongBits(getNetTxRate())
          == java.lang.Double.doubleToLongBits(
              other.getNetTxRate()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskId());
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostname().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + CPU_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpuLimit());
      hash = (37 * hash) + CPU_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpuRequest());
      hash = (37 * hash) + CPU_USAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpuUsage());
      hash = (37 * hash) + MEM_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemLimit());
      hash = (37 * hash) + MEM_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemRequest());
      hash = (37 * hash) + MEM_USAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemUsage());
      hash = (37 * hash) + MEM_RSS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemRss());
      hash = (37 * hash) + MEM_CACHE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemCache());
      hash = (37 * hash) + MEM_WORKING_SET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemWorkingSet());
      hash = (37 * hash) + MEM_PAGE_FAULTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemPageFaults());
      hash = (37 * hash) + MEM_PAGE_FAULTS_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMemPageFaultsRate()));
      hash = (37 * hash) + MAJOR_PAGE_FAULTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMajorPageFaults());
      hash = (37 * hash) + MAJOR_PAGE_FAULTS_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMajorPageFaultsRate()));
      hash = (37 * hash) + NET_RX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNetRx());
      hash = (37 * hash) + NET_RX_ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNetRxErrors());
      hash = (37 * hash) + NET_RX_ERRORS_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNetRxErrorsRate()));
      hash = (37 * hash) + NET_RX_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNetRxRate()));
      hash = (37 * hash) + NET_TX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNetTx());
      hash = (37 * hash) + NET_TX_ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNetTxErrors());
      hash = (37 * hash) + NET_TX_ERRORS_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNetTxErrorsRate()));
      hash = (37 * hash) + NET_TX_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNetTxRate()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.TaskStatsOuterClass.TaskStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(firmament.TaskStatsOuterClass.TaskStats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code firmament.TaskStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:firmament.TaskStats)
        firmament.TaskStatsOuterClass.TaskStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return firmament.TaskStatsOuterClass.internal_static_firmament_TaskStats_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return firmament.TaskStatsOuterClass.internal_static_firmament_TaskStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                firmament.TaskStatsOuterClass.TaskStats.class, firmament.TaskStatsOuterClass.TaskStats.Builder.class);
      }

      // Construct using firmament.TaskStatsOuterClass.TaskStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskId_ = 0L;

        hostname_ = "";

        timestamp_ = 0L;

        cpuLimit_ = 0L;

        cpuRequest_ = 0L;

        cpuUsage_ = 0L;

        memLimit_ = 0L;

        memRequest_ = 0L;

        memUsage_ = 0L;

        memRss_ = 0L;

        memCache_ = 0L;

        memWorkingSet_ = 0L;

        memPageFaults_ = 0L;

        memPageFaultsRate_ = 0D;

        majorPageFaults_ = 0L;

        majorPageFaultsRate_ = 0D;

        netRx_ = 0L;

        netRxErrors_ = 0L;

        netRxErrorsRate_ = 0D;

        netRxRate_ = 0D;

        netTx_ = 0L;

        netTxErrors_ = 0L;

        netTxErrorsRate_ = 0D;

        netTxRate_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return firmament.TaskStatsOuterClass.internal_static_firmament_TaskStats_descriptor;
      }

      public firmament.TaskStatsOuterClass.TaskStats getDefaultInstanceForType() {
        return firmament.TaskStatsOuterClass.TaskStats.getDefaultInstance();
      }

      public firmament.TaskStatsOuterClass.TaskStats build() {
        firmament.TaskStatsOuterClass.TaskStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public firmament.TaskStatsOuterClass.TaskStats buildPartial() {
        firmament.TaskStatsOuterClass.TaskStats result = new firmament.TaskStatsOuterClass.TaskStats(this);
        result.taskId_ = taskId_;
        result.hostname_ = hostname_;
        result.timestamp_ = timestamp_;
        result.cpuLimit_ = cpuLimit_;
        result.cpuRequest_ = cpuRequest_;
        result.cpuUsage_ = cpuUsage_;
        result.memLimit_ = memLimit_;
        result.memRequest_ = memRequest_;
        result.memUsage_ = memUsage_;
        result.memRss_ = memRss_;
        result.memCache_ = memCache_;
        result.memWorkingSet_ = memWorkingSet_;
        result.memPageFaults_ = memPageFaults_;
        result.memPageFaultsRate_ = memPageFaultsRate_;
        result.majorPageFaults_ = majorPageFaults_;
        result.majorPageFaultsRate_ = majorPageFaultsRate_;
        result.netRx_ = netRx_;
        result.netRxErrors_ = netRxErrors_;
        result.netRxErrorsRate_ = netRxErrorsRate_;
        result.netRxRate_ = netRxRate_;
        result.netTx_ = netTx_;
        result.netTxErrors_ = netTxErrors_;
        result.netTxErrorsRate_ = netTxErrorsRate_;
        result.netTxRate_ = netTxRate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof firmament.TaskStatsOuterClass.TaskStats) {
          return mergeFrom((firmament.TaskStatsOuterClass.TaskStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(firmament.TaskStatsOuterClass.TaskStats other) {
        if (other == firmament.TaskStatsOuterClass.TaskStats.getDefaultInstance()) return this;
        if (other.getTaskId() != 0L) {
          setTaskId(other.getTaskId());
        }
        if (!other.getHostname().isEmpty()) {
          hostname_ = other.hostname_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getCpuLimit() != 0L) {
          setCpuLimit(other.getCpuLimit());
        }
        if (other.getCpuRequest() != 0L) {
          setCpuRequest(other.getCpuRequest());
        }
        if (other.getCpuUsage() != 0L) {
          setCpuUsage(other.getCpuUsage());
        }
        if (other.getMemLimit() != 0L) {
          setMemLimit(other.getMemLimit());
        }
        if (other.getMemRequest() != 0L) {
          setMemRequest(other.getMemRequest());
        }
        if (other.getMemUsage() != 0L) {
          setMemUsage(other.getMemUsage());
        }
        if (other.getMemRss() != 0L) {
          setMemRss(other.getMemRss());
        }
        if (other.getMemCache() != 0L) {
          setMemCache(other.getMemCache());
        }
        if (other.getMemWorkingSet() != 0L) {
          setMemWorkingSet(other.getMemWorkingSet());
        }
        if (other.getMemPageFaults() != 0L) {
          setMemPageFaults(other.getMemPageFaults());
        }
        if (other.getMemPageFaultsRate() != 0D) {
          setMemPageFaultsRate(other.getMemPageFaultsRate());
        }
        if (other.getMajorPageFaults() != 0L) {
          setMajorPageFaults(other.getMajorPageFaults());
        }
        if (other.getMajorPageFaultsRate() != 0D) {
          setMajorPageFaultsRate(other.getMajorPageFaultsRate());
        }
        if (other.getNetRx() != 0L) {
          setNetRx(other.getNetRx());
        }
        if (other.getNetRxErrors() != 0L) {
          setNetRxErrors(other.getNetRxErrors());
        }
        if (other.getNetRxErrorsRate() != 0D) {
          setNetRxErrorsRate(other.getNetRxErrorsRate());
        }
        if (other.getNetRxRate() != 0D) {
          setNetRxRate(other.getNetRxRate());
        }
        if (other.getNetTx() != 0L) {
          setNetTx(other.getNetTx());
        }
        if (other.getNetTxErrors() != 0L) {
          setNetTxErrors(other.getNetTxErrors());
        }
        if (other.getNetTxErrorsRate() != 0D) {
          setNetTxErrorsRate(other.getNetTxErrorsRate());
        }
        if (other.getNetTxRate() != 0D) {
          setNetTxRate(other.getNetTxRate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        firmament.TaskStatsOuterClass.TaskStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (firmament.TaskStatsOuterClass.TaskStats) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long taskId_ ;
      /**
       * <code>optional uint64 task_id = 1;</code>
       */
      public long getTaskId() {
        return taskId_;
      }
      /**
       * <code>optional uint64 task_id = 1;</code>
       */
      public Builder setTaskId(long value) {
        
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 task_id = 1;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object hostname_ = "";
      /**
       * <code>optional string hostname = 2;</code>
       */
      public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hostname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hostname = 2;</code>
       */
      public Builder setHostname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hostname = 2;</code>
       */
      public Builder clearHostname() {
        
        hostname_ = getDefaultInstance().getHostname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hostname = 2;</code>
       */
      public Builder setHostnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostname_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long cpuLimit_ ;
      /**
       * <pre>
       * CPU stats in millicores.
       * </pre>
       *
       * <code>optional int64 cpu_limit = 4;</code>
       */
      public long getCpuLimit() {
        return cpuLimit_;
      }
      /**
       * <pre>
       * CPU stats in millicores.
       * </pre>
       *
       * <code>optional int64 cpu_limit = 4;</code>
       */
      public Builder setCpuLimit(long value) {
        
        cpuLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CPU stats in millicores.
       * </pre>
       *
       * <code>optional int64 cpu_limit = 4;</code>
       */
      public Builder clearCpuLimit() {
        
        cpuLimit_ = 0L;
        onChanged();
        return this;
      }

      private long cpuRequest_ ;
      /**
       * <code>optional int64 cpu_request = 5;</code>
       */
      public long getCpuRequest() {
        return cpuRequest_;
      }
      /**
       * <code>optional int64 cpu_request = 5;</code>
       */
      public Builder setCpuRequest(long value) {
        
        cpuRequest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cpu_request = 5;</code>
       */
      public Builder clearCpuRequest() {
        
        cpuRequest_ = 0L;
        onChanged();
        return this;
      }

      private long cpuUsage_ ;
      /**
       * <code>optional int64 cpu_usage = 6;</code>
       */
      public long getCpuUsage() {
        return cpuUsage_;
      }
      /**
       * <code>optional int64 cpu_usage = 6;</code>
       */
      public Builder setCpuUsage(long value) {
        
        cpuUsage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cpu_usage = 6;</code>
       */
      public Builder clearCpuUsage() {
        
        cpuUsage_ = 0L;
        onChanged();
        return this;
      }

      private long memLimit_ ;
      /**
       * <pre>
       * Memory stats in Kb.
       * </pre>
       *
       * <code>optional int64 mem_limit = 7;</code>
       */
      public long getMemLimit() {
        return memLimit_;
      }
      /**
       * <pre>
       * Memory stats in Kb.
       * </pre>
       *
       * <code>optional int64 mem_limit = 7;</code>
       */
      public Builder setMemLimit(long value) {
        
        memLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Memory stats in Kb.
       * </pre>
       *
       * <code>optional int64 mem_limit = 7;</code>
       */
      public Builder clearMemLimit() {
        
        memLimit_ = 0L;
        onChanged();
        return this;
      }

      private long memRequest_ ;
      /**
       * <code>optional int64 mem_request = 8;</code>
       */
      public long getMemRequest() {
        return memRequest_;
      }
      /**
       * <code>optional int64 mem_request = 8;</code>
       */
      public Builder setMemRequest(long value) {
        
        memRequest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mem_request = 8;</code>
       */
      public Builder clearMemRequest() {
        
        memRequest_ = 0L;
        onChanged();
        return this;
      }

      private long memUsage_ ;
      /**
       * <code>optional int64 mem_usage = 9;</code>
       */
      public long getMemUsage() {
        return memUsage_;
      }
      /**
       * <code>optional int64 mem_usage = 9;</code>
       */
      public Builder setMemUsage(long value) {
        
        memUsage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mem_usage = 9;</code>
       */
      public Builder clearMemUsage() {
        
        memUsage_ = 0L;
        onChanged();
        return this;
      }

      private long memRss_ ;
      /**
       * <code>optional int64 mem_rss = 10;</code>
       */
      public long getMemRss() {
        return memRss_;
      }
      /**
       * <code>optional int64 mem_rss = 10;</code>
       */
      public Builder setMemRss(long value) {
        
        memRss_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mem_rss = 10;</code>
       */
      public Builder clearMemRss() {
        
        memRss_ = 0L;
        onChanged();
        return this;
      }

      private long memCache_ ;
      /**
       * <code>optional int64 mem_cache = 11;</code>
       */
      public long getMemCache() {
        return memCache_;
      }
      /**
       * <code>optional int64 mem_cache = 11;</code>
       */
      public Builder setMemCache(long value) {
        
        memCache_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mem_cache = 11;</code>
       */
      public Builder clearMemCache() {
        
        memCache_ = 0L;
        onChanged();
        return this;
      }

      private long memWorkingSet_ ;
      /**
       * <code>optional int64 mem_working_set = 12;</code>
       */
      public long getMemWorkingSet() {
        return memWorkingSet_;
      }
      /**
       * <code>optional int64 mem_working_set = 12;</code>
       */
      public Builder setMemWorkingSet(long value) {
        
        memWorkingSet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mem_working_set = 12;</code>
       */
      public Builder clearMemWorkingSet() {
        
        memWorkingSet_ = 0L;
        onChanged();
        return this;
      }

      private long memPageFaults_ ;
      /**
       * <code>optional int64 mem_page_faults = 13;</code>
       */
      public long getMemPageFaults() {
        return memPageFaults_;
      }
      /**
       * <code>optional int64 mem_page_faults = 13;</code>
       */
      public Builder setMemPageFaults(long value) {
        
        memPageFaults_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mem_page_faults = 13;</code>
       */
      public Builder clearMemPageFaults() {
        
        memPageFaults_ = 0L;
        onChanged();
        return this;
      }

      private double memPageFaultsRate_ ;
      /**
       * <code>optional double mem_page_faults_rate = 14;</code>
       */
      public double getMemPageFaultsRate() {
        return memPageFaultsRate_;
      }
      /**
       * <code>optional double mem_page_faults_rate = 14;</code>
       */
      public Builder setMemPageFaultsRate(double value) {
        
        memPageFaultsRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double mem_page_faults_rate = 14;</code>
       */
      public Builder clearMemPageFaultsRate() {
        
        memPageFaultsRate_ = 0D;
        onChanged();
        return this;
      }

      private long majorPageFaults_ ;
      /**
       * <code>optional int64 major_page_faults = 15;</code>
       */
      public long getMajorPageFaults() {
        return majorPageFaults_;
      }
      /**
       * <code>optional int64 major_page_faults = 15;</code>
       */
      public Builder setMajorPageFaults(long value) {
        
        majorPageFaults_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 major_page_faults = 15;</code>
       */
      public Builder clearMajorPageFaults() {
        
        majorPageFaults_ = 0L;
        onChanged();
        return this;
      }

      private double majorPageFaultsRate_ ;
      /**
       * <code>optional double major_page_faults_rate = 16;</code>
       */
      public double getMajorPageFaultsRate() {
        return majorPageFaultsRate_;
      }
      /**
       * <code>optional double major_page_faults_rate = 16;</code>
       */
      public Builder setMajorPageFaultsRate(double value) {
        
        majorPageFaultsRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double major_page_faults_rate = 16;</code>
       */
      public Builder clearMajorPageFaultsRate() {
        
        majorPageFaultsRate_ = 0D;
        onChanged();
        return this;
      }

      private long netRx_ ;
      /**
       * <pre>
       * Network stats in Kb.
       * </pre>
       *
       * <code>optional int64 net_rx = 17;</code>
       */
      public long getNetRx() {
        return netRx_;
      }
      /**
       * <pre>
       * Network stats in Kb.
       * </pre>
       *
       * <code>optional int64 net_rx = 17;</code>
       */
      public Builder setNetRx(long value) {
        
        netRx_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Network stats in Kb.
       * </pre>
       *
       * <code>optional int64 net_rx = 17;</code>
       */
      public Builder clearNetRx() {
        
        netRx_ = 0L;
        onChanged();
        return this;
      }

      private long netRxErrors_ ;
      /**
       * <code>optional int64 net_rx_errors = 18;</code>
       */
      public long getNetRxErrors() {
        return netRxErrors_;
      }
      /**
       * <code>optional int64 net_rx_errors = 18;</code>
       */
      public Builder setNetRxErrors(long value) {
        
        netRxErrors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 net_rx_errors = 18;</code>
       */
      public Builder clearNetRxErrors() {
        
        netRxErrors_ = 0L;
        onChanged();
        return this;
      }

      private double netRxErrorsRate_ ;
      /**
       * <code>optional double net_rx_errors_rate = 19;</code>
       */
      public double getNetRxErrorsRate() {
        return netRxErrorsRate_;
      }
      /**
       * <code>optional double net_rx_errors_rate = 19;</code>
       */
      public Builder setNetRxErrorsRate(double value) {
        
        netRxErrorsRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double net_rx_errors_rate = 19;</code>
       */
      public Builder clearNetRxErrorsRate() {
        
        netRxErrorsRate_ = 0D;
        onChanged();
        return this;
      }

      private double netRxRate_ ;
      /**
       * <code>optional double net_rx_rate = 20;</code>
       */
      public double getNetRxRate() {
        return netRxRate_;
      }
      /**
       * <code>optional double net_rx_rate = 20;</code>
       */
      public Builder setNetRxRate(double value) {
        
        netRxRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double net_rx_rate = 20;</code>
       */
      public Builder clearNetRxRate() {
        
        netRxRate_ = 0D;
        onChanged();
        return this;
      }

      private long netTx_ ;
      /**
       * <code>optional int64 net_tx = 21;</code>
       */
      public long getNetTx() {
        return netTx_;
      }
      /**
       * <code>optional int64 net_tx = 21;</code>
       */
      public Builder setNetTx(long value) {
        
        netTx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 net_tx = 21;</code>
       */
      public Builder clearNetTx() {
        
        netTx_ = 0L;
        onChanged();
        return this;
      }

      private long netTxErrors_ ;
      /**
       * <code>optional int64 net_tx_errors = 22;</code>
       */
      public long getNetTxErrors() {
        return netTxErrors_;
      }
      /**
       * <code>optional int64 net_tx_errors = 22;</code>
       */
      public Builder setNetTxErrors(long value) {
        
        netTxErrors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 net_tx_errors = 22;</code>
       */
      public Builder clearNetTxErrors() {
        
        netTxErrors_ = 0L;
        onChanged();
        return this;
      }

      private double netTxErrorsRate_ ;
      /**
       * <code>optional double net_tx_errors_rate = 23;</code>
       */
      public double getNetTxErrorsRate() {
        return netTxErrorsRate_;
      }
      /**
       * <code>optional double net_tx_errors_rate = 23;</code>
       */
      public Builder setNetTxErrorsRate(double value) {
        
        netTxErrorsRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double net_tx_errors_rate = 23;</code>
       */
      public Builder clearNetTxErrorsRate() {
        
        netTxErrorsRate_ = 0D;
        onChanged();
        return this;
      }

      private double netTxRate_ ;
      /**
       * <code>optional double net_tx_rate = 24;</code>
       */
      public double getNetTxRate() {
        return netTxRate_;
      }
      /**
       * <code>optional double net_tx_rate = 24;</code>
       */
      public Builder setNetTxRate(double value) {
        
        netTxRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double net_tx_rate = 24;</code>
       */
      public Builder clearNetTxRate() {
        
        netTxRate_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:firmament.TaskStats)
    }

    // @@protoc_insertion_point(class_scope:firmament.TaskStats)
    private static final firmament.TaskStatsOuterClass.TaskStats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new firmament.TaskStatsOuterClass.TaskStats();
    }

    public static firmament.TaskStatsOuterClass.TaskStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskStats>
        PARSER = new com.google.protobuf.AbstractParser<TaskStats>() {
      public TaskStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TaskStats(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskStats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskStats> getParserForType() {
      return PARSER;
    }

    public firmament.TaskStatsOuterClass.TaskStats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firmament_TaskStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firmament_TaskStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020task_stats.proto\022\tfirmament\"\226\004\n\tTaskSt" +
      "ats\022\017\n\007task_id\030\001 \001(\004\022\020\n\010hostname\030\002 \001(\t\022\021" +
      "\n\ttimestamp\030\003 \001(\004\022\021\n\tcpu_limit\030\004 \001(\003\022\023\n\013" +
      "cpu_request\030\005 \001(\003\022\021\n\tcpu_usage\030\006 \001(\003\022\021\n\t" +
      "mem_limit\030\007 \001(\003\022\023\n\013mem_request\030\010 \001(\003\022\021\n\t" +
      "mem_usage\030\t \001(\003\022\017\n\007mem_rss\030\n \001(\003\022\021\n\tmem_" +
      "cache\030\013 \001(\003\022\027\n\017mem_working_set\030\014 \001(\003\022\027\n\017" +
      "mem_page_faults\030\r \001(\003\022\034\n\024mem_page_faults" +
      "_rate\030\016 \001(\001\022\031\n\021major_page_faults\030\017 \001(\003\022\036" +
      "\n\026major_page_faults_rate\030\020 \001(\001\022\016\n\006net_rx",
      "\030\021 \001(\003\022\025\n\rnet_rx_errors\030\022 \001(\003\022\032\n\022net_rx_" +
      "errors_rate\030\023 \001(\001\022\023\n\013net_rx_rate\030\024 \001(\001\022\016" +
      "\n\006net_tx\030\025 \001(\003\022\025\n\rnet_tx_errors\030\026 \001(\003\022\032\n" +
      "\022net_tx_errors_rate\030\027 \001(\001\022\023\n\013net_tx_rate" +
      "\030\030 \001(\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_firmament_TaskStats_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_firmament_TaskStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firmament_TaskStats_descriptor,
        new java.lang.String[] { "TaskId", "Hostname", "Timestamp", "CpuLimit", "CpuRequest", "CpuUsage", "MemLimit", "MemRequest", "MemUsage", "MemRss", "MemCache", "MemWorkingSet", "MemPageFaults", "MemPageFaultsRate", "MajorPageFaults", "MajorPageFaultsRate", "NetRx", "NetRxErrors", "NetRxErrorsRate", "NetRxRate", "NetTx", "NetTxErrors", "NetTxErrorsRate", "NetTxRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
