// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: whare_map_stats.proto

package firmament;

public final class WhareMapStatsOuterClass {
  private WhareMapStatsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WhareMapStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:firmament.WhareMapStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 num_idle = 1;</code>
     */
    long getNumIdle();

    /**
     * <code>optional uint64 num_devils = 2;</code>
     */
    long getNumDevils();

    /**
     * <code>optional uint64 num_rabbits = 3;</code>
     */
    long getNumRabbits();

    /**
     * <code>optional uint64 num_sheep = 4;</code>
     */
    long getNumSheep();

    /**
     * <code>optional uint64 num_turtles = 5;</code>
     */
    long getNumTurtles();
  }
  /**
   * Protobuf type {@code firmament.WhareMapStats}
   */
  public  static final class WhareMapStats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:firmament.WhareMapStats)
      WhareMapStatsOrBuilder {
    // Use WhareMapStats.newBuilder() to construct.
    private WhareMapStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WhareMapStats() {
      numIdle_ = 0L;
      numDevils_ = 0L;
      numRabbits_ = 0L;
      numSheep_ = 0L;
      numTurtles_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WhareMapStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              numIdle_ = input.readUInt64();
              break;
            }
            case 16: {

              numDevils_ = input.readUInt64();
              break;
            }
            case 24: {

              numRabbits_ = input.readUInt64();
              break;
            }
            case 32: {

              numSheep_ = input.readUInt64();
              break;
            }
            case 40: {

              numTurtles_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return firmament.WhareMapStatsOuterClass.internal_static_firmament_WhareMapStats_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return firmament.WhareMapStatsOuterClass.internal_static_firmament_WhareMapStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              firmament.WhareMapStatsOuterClass.WhareMapStats.class, firmament.WhareMapStatsOuterClass.WhareMapStats.Builder.class);
    }

    public static final int NUM_IDLE_FIELD_NUMBER = 1;
    private long numIdle_;
    /**
     * <code>optional uint64 num_idle = 1;</code>
     */
    public long getNumIdle() {
      return numIdle_;
    }

    public static final int NUM_DEVILS_FIELD_NUMBER = 2;
    private long numDevils_;
    /**
     * <code>optional uint64 num_devils = 2;</code>
     */
    public long getNumDevils() {
      return numDevils_;
    }

    public static final int NUM_RABBITS_FIELD_NUMBER = 3;
    private long numRabbits_;
    /**
     * <code>optional uint64 num_rabbits = 3;</code>
     */
    public long getNumRabbits() {
      return numRabbits_;
    }

    public static final int NUM_SHEEP_FIELD_NUMBER = 4;
    private long numSheep_;
    /**
     * <code>optional uint64 num_sheep = 4;</code>
     */
    public long getNumSheep() {
      return numSheep_;
    }

    public static final int NUM_TURTLES_FIELD_NUMBER = 5;
    private long numTurtles_;
    /**
     * <code>optional uint64 num_turtles = 5;</code>
     */
    public long getNumTurtles() {
      return numTurtles_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numIdle_ != 0L) {
        output.writeUInt64(1, numIdle_);
      }
      if (numDevils_ != 0L) {
        output.writeUInt64(2, numDevils_);
      }
      if (numRabbits_ != 0L) {
        output.writeUInt64(3, numRabbits_);
      }
      if (numSheep_ != 0L) {
        output.writeUInt64(4, numSheep_);
      }
      if (numTurtles_ != 0L) {
        output.writeUInt64(5, numTurtles_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numIdle_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, numIdle_);
      }
      if (numDevils_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, numDevils_);
      }
      if (numRabbits_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, numRabbits_);
      }
      if (numSheep_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, numSheep_);
      }
      if (numTurtles_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, numTurtles_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof firmament.WhareMapStatsOuterClass.WhareMapStats)) {
        return super.equals(obj);
      }
      firmament.WhareMapStatsOuterClass.WhareMapStats other = (firmament.WhareMapStatsOuterClass.WhareMapStats) obj;

      boolean result = true;
      result = result && (getNumIdle()
          == other.getNumIdle());
      result = result && (getNumDevils()
          == other.getNumDevils());
      result = result && (getNumRabbits()
          == other.getNumRabbits());
      result = result && (getNumSheep()
          == other.getNumSheep());
      result = result && (getNumTurtles()
          == other.getNumTurtles());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NUM_IDLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumIdle());
      hash = (37 * hash) + NUM_DEVILS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumDevils());
      hash = (37 * hash) + NUM_RABBITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumRabbits());
      hash = (37 * hash) + NUM_SHEEP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumSheep());
      hash = (37 * hash) + NUM_TURTLES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumTurtles());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static firmament.WhareMapStatsOuterClass.WhareMapStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(firmament.WhareMapStatsOuterClass.WhareMapStats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code firmament.WhareMapStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:firmament.WhareMapStats)
        firmament.WhareMapStatsOuterClass.WhareMapStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return firmament.WhareMapStatsOuterClass.internal_static_firmament_WhareMapStats_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return firmament.WhareMapStatsOuterClass.internal_static_firmament_WhareMapStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                firmament.WhareMapStatsOuterClass.WhareMapStats.class, firmament.WhareMapStatsOuterClass.WhareMapStats.Builder.class);
      }

      // Construct using firmament.WhareMapStatsOuterClass.WhareMapStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        numIdle_ = 0L;

        numDevils_ = 0L;

        numRabbits_ = 0L;

        numSheep_ = 0L;

        numTurtles_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return firmament.WhareMapStatsOuterClass.internal_static_firmament_WhareMapStats_descriptor;
      }

      public firmament.WhareMapStatsOuterClass.WhareMapStats getDefaultInstanceForType() {
        return firmament.WhareMapStatsOuterClass.WhareMapStats.getDefaultInstance();
      }

      public firmament.WhareMapStatsOuterClass.WhareMapStats build() {
        firmament.WhareMapStatsOuterClass.WhareMapStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public firmament.WhareMapStatsOuterClass.WhareMapStats buildPartial() {
        firmament.WhareMapStatsOuterClass.WhareMapStats result = new firmament.WhareMapStatsOuterClass.WhareMapStats(this);
        result.numIdle_ = numIdle_;
        result.numDevils_ = numDevils_;
        result.numRabbits_ = numRabbits_;
        result.numSheep_ = numSheep_;
        result.numTurtles_ = numTurtles_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof firmament.WhareMapStatsOuterClass.WhareMapStats) {
          return mergeFrom((firmament.WhareMapStatsOuterClass.WhareMapStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(firmament.WhareMapStatsOuterClass.WhareMapStats other) {
        if (other == firmament.WhareMapStatsOuterClass.WhareMapStats.getDefaultInstance()) return this;
        if (other.getNumIdle() != 0L) {
          setNumIdle(other.getNumIdle());
        }
        if (other.getNumDevils() != 0L) {
          setNumDevils(other.getNumDevils());
        }
        if (other.getNumRabbits() != 0L) {
          setNumRabbits(other.getNumRabbits());
        }
        if (other.getNumSheep() != 0L) {
          setNumSheep(other.getNumSheep());
        }
        if (other.getNumTurtles() != 0L) {
          setNumTurtles(other.getNumTurtles());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        firmament.WhareMapStatsOuterClass.WhareMapStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (firmament.WhareMapStatsOuterClass.WhareMapStats) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long numIdle_ ;
      /**
       * <code>optional uint64 num_idle = 1;</code>
       */
      public long getNumIdle() {
        return numIdle_;
      }
      /**
       * <code>optional uint64 num_idle = 1;</code>
       */
      public Builder setNumIdle(long value) {
        
        numIdle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 num_idle = 1;</code>
       */
      public Builder clearNumIdle() {
        
        numIdle_ = 0L;
        onChanged();
        return this;
      }

      private long numDevils_ ;
      /**
       * <code>optional uint64 num_devils = 2;</code>
       */
      public long getNumDevils() {
        return numDevils_;
      }
      /**
       * <code>optional uint64 num_devils = 2;</code>
       */
      public Builder setNumDevils(long value) {
        
        numDevils_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 num_devils = 2;</code>
       */
      public Builder clearNumDevils() {
        
        numDevils_ = 0L;
        onChanged();
        return this;
      }

      private long numRabbits_ ;
      /**
       * <code>optional uint64 num_rabbits = 3;</code>
       */
      public long getNumRabbits() {
        return numRabbits_;
      }
      /**
       * <code>optional uint64 num_rabbits = 3;</code>
       */
      public Builder setNumRabbits(long value) {
        
        numRabbits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 num_rabbits = 3;</code>
       */
      public Builder clearNumRabbits() {
        
        numRabbits_ = 0L;
        onChanged();
        return this;
      }

      private long numSheep_ ;
      /**
       * <code>optional uint64 num_sheep = 4;</code>
       */
      public long getNumSheep() {
        return numSheep_;
      }
      /**
       * <code>optional uint64 num_sheep = 4;</code>
       */
      public Builder setNumSheep(long value) {
        
        numSheep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 num_sheep = 4;</code>
       */
      public Builder clearNumSheep() {
        
        numSheep_ = 0L;
        onChanged();
        return this;
      }

      private long numTurtles_ ;
      /**
       * <code>optional uint64 num_turtles = 5;</code>
       */
      public long getNumTurtles() {
        return numTurtles_;
      }
      /**
       * <code>optional uint64 num_turtles = 5;</code>
       */
      public Builder setNumTurtles(long value) {
        
        numTurtles_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 num_turtles = 5;</code>
       */
      public Builder clearNumTurtles() {
        
        numTurtles_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:firmament.WhareMapStats)
    }

    // @@protoc_insertion_point(class_scope:firmament.WhareMapStats)
    private static final firmament.WhareMapStatsOuterClass.WhareMapStats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new firmament.WhareMapStatsOuterClass.WhareMapStats();
    }

    public static firmament.WhareMapStatsOuterClass.WhareMapStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WhareMapStats>
        PARSER = new com.google.protobuf.AbstractParser<WhareMapStats>() {
      public WhareMapStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WhareMapStats(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WhareMapStats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WhareMapStats> getParserForType() {
      return PARSER;
    }

    public firmament.WhareMapStatsOuterClass.WhareMapStats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firmament_WhareMapStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firmament_WhareMapStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025whare_map_stats.proto\022\tfirmament\"r\n\rWh" +
      "areMapStats\022\020\n\010num_idle\030\001 \001(\004\022\022\n\nnum_dev" +
      "ils\030\002 \001(\004\022\023\n\013num_rabbits\030\003 \001(\004\022\021\n\tnum_sh" +
      "eep\030\004 \001(\004\022\023\n\013num_turtles\030\005 \001(\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_firmament_WhareMapStats_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_firmament_WhareMapStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firmament_WhareMapStats_descriptor,
        new java.lang.String[] { "NumIdle", "NumDevils", "NumRabbits", "NumSheep", "NumTurtles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
